### PR TITLE
Extend decentlab vendor fields 

### PR DESCRIPTION
**Pull request by mjamescompton**
#### Summary

As part of the new device repository website we will be generating partner landing pages. These pages are lacking in company data. 

Screenshot 2021-04-29 at 10 49 51

Here is an example how we could extend the vendor data in the repo. 
An alternative could be to include it here `vendor/index.yaml` but I did not want to over populate this file.

#### Changes

- Add vendor `description`, `vendorURL` and `social` links

#### Notes for Reviewers

Other suggestions included including vendor `location` do you have a good suggestion for a formatted way of including this? 

#### Release Notes

- Add vendor `description`, `vendorURL` and `social` links to decentlab

### CODE REVIEW

**Comment by johanstokking** [comment]
Looks good to me. We just need to extend the schema for the vendor index file.

Are these the fields that we need? Is there anything else? What other social channels do we want if any?

What kind of location do we want? I can imagine more like the markets that the device vendor is selling to?

We already have this per end device, and we can reuse this list: https://github.com/lorawan-schema/draft-devices/blob/6e9f95062841403e34ce12393dab519c39ec7511/schema.json#L1068-L1086 ?

**Comment by cBashTN** [comment]
Instead of (or in addition to) ```location```: How about ```vendorContactURL```?
```vendorContactURL: https://www.decentlab.com/about``` or 
```vendorContactURL: https://keller-druck.com/en/contact```

Is ```github``` a social?  :-)

The cool kids have it:

```
social:  
  github: https://github.com/decentlab
```  

or

```
social:  
  github: https://github.com/KELLERAGfuerDruckmesstechnik
```

**Comment by mjamescompton** [comment]
@johanstokking I've updated the schema here, and added decentlab description and social links as an example to `vendor/index.yaml`. 

Also added a pr to draft-devices https://github.com/lorawan-schema/draft-devices/pull/18

I'm leaving it up to @Sharan2395 to define the location field in new issue.

**Review by johanstokking — APPROVED** [review]

**Comment by johanstokking** [comment]
@mjamescompton rebased and updated this to use the handles.

Please include some instructions in README.

Also don't bump the `package-lock.json` version file, we're still on:

```
- Node.js version 14.x
- npm version 6.x
```

**Pull request merged**
