### PR TITLE
Adding Temperature sensor, current and voltage sensor and a smartplug

### PR DESCRIPTION
**Pull request by Ben199-cpu**
#### Summary

Add remote temperature sensor, current and voltage sensor and a smartplug

#### Changes

- ...
- ...

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Comment by Jaime-Trinidad** [comment]
Hi @Ben199-cpu package-lock.json can't be modify please verify this, also resolve conflicts on the branch.

**Comment by Jaime-Trinidad** [comment]
@Ben199-cpu please run make validate fmt

**Comment by Ben199-cpu** [comment]
It's done !
________________________________
De : Jaime Trinidad ***@***.***>
Envoyé : jeudi 24 juin 2021 11:18
À : TheThingsNetwork/lorawan-devices ***@***.***>
Cc : MOYAUX Benoit ***@***.***>; Mention ***@***.***>
Objet : Re: [TheThingsNetwork/lorawan-devices] Adding Temperature sensor, current and voltage sensor and a smartplug (#227)


@Ben199-cpu<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBen199-cpu&data=04%7C01%7Cbenoit.moyaux%40ecole.ensicaen.fr%7Cb6cf581bca7b40c0e80f08d936f10ca8%7C430c3e75ff03445fb3f4ae2809a0b10b%7C1%7C0%7C637601231190846304%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SGucK2MJGOeP%2FAkIZLNQiDJC7wEtdtcnUvMfeWEKwBY%3D&reserved=0> please run make validate fmt

**Review by Jaime-Trinidad — APPROVED** [review]
files and changes looks fine

**Pull request merged**
