### PR TITLE
Add SenseCAP Indicator and update the decoder of SenseCAP tracker

### PR DESCRIPTION
**Pull request by Kway99**
#### Summary

Add SenseCAP Indicator and update the decoder of SenseCAP tracker

#### Changes

Add SenseCAP Indicator and update the decoder of SenseCAP tracker

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Comment by Kway99** [comment]
Hi TTN team,

Hope you're doing well! This is Lee from Seeed SenseCAP team.
I have added the sensecap indicator and update the decoder of t1000 tracker a/b. Please kindly have a check!
Your suggestion is much appreciated! Thanks~

Best Regards!

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by Jaime-Trinidad** [comment]
hi @Kway99 please run `make validate fmt`

**Comment by Kway99** [comment]
Hi @Jaime-Trinidad , thanks for your attention~ When I run `make validate fmt` , it just shows this:
WeChatWorkScreenshot_4d507227-1a27-4ea5-a940-db003004cbe4
It seems stuck at other brands.

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by scarolan** [comment]
TTN crew can you help out here and merge this PR?  I spent hours tinkering with this device only to find out the decoder config in your catalog is out of date.

**Comment by Kway99** [comment]
Hello @Jaime-Trinidad , could you please help me with this pull request? any suggestions and inputs are much appreciated!!

**Comment by LDannijs** [comment]
Hello @Kway99 i'm able to help out as well. Could you try running `make validate fmt -i`? Hopefully it should then run through it all.

**Comment by Kway99** [comment]
Hi @Jaime-Trinidad  , we have corrected the required format. Could you please review and merge it? Thanks for your time!

**Review by Jaime-Trinidad — APPROVED** [review]

**Pull request merged**
