### PR TITLE
Add more Dragino devices 

### PR DESCRIPTION
**Pull request by dragino**
#### Summary

Add more devices from Dragino

#### Changes

- Add all new devices up to date
- Fix previous codec bug

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Comment by Jaime-Trinidad** [comment]
Hi @dragino your ABP thee best will be not to add abp device as are the same you already have, instead of that you can add abp in device.yaml file, e.g.: `lbt1.yaml`


 profiles:

      EU863-870:
        // Unique identifier of the profile (lowercase, alphanumeric with dashes, max 36 characters)
        id: eu868-profile
        lorawanCertified: true
        codec: lbt1-codec
      EU433:
        id: eu433-profile
        lorawanCertified: true
        codec: lbt1-codec
Add below:
  // Activation By Personalization

            - version: 'lbt1 abp'
               numeric: 2
               hardwareVersions:
                      - '1.0'
              profiles:
                  EU863-870:
                     id: eu868-a-abp-profile
                     lorawanCertified: true
                    codec: lbt1-codec

Making it this way users only will have one device to select and abp profile option will display:

Screen Shot 2021-08-31 at 9 37 34

**Comment by Jaime-Trinidad** [comment]
@dragino I update lbt1 as an example, now in lbt1 is also abp profile and I delete lbt1-abp file, take a look if this is right for you.

**Comment by Jaime-Trinidad** [comment]
Hi @dragino any update here, you need any help with this?

**Comment by dragino** [comment]
> 
> 
> Hi @dragino any update here, you need any help with this?

Update. please check. Thank You !

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by dragino** [comment]
@Jaime-Trinidad 
Now shows "Validate Expected — Waiting for status to be reported"
Do we do something in our side now?

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by dragino** [comment]
> 
> Hi @dragino there were many conflicts in the files, I just fixed them.
Hi, @Jaime-Trinidad Thanks for the help!

**Comment by mjamescompton** [comment]
@Jaime-Trinidad somethings really out of sync here, the pr is removing previous work such as changing the go version in `.github/workflows/validate.yml`, does not look like it can be fixed with simple rebase or merge. I would create a new branch based on TheThingsNetwork/lorawan-devices:master then cherry-pick the commit you want from this pr

**Comment by Jaime-Trinidad** [comment]
Hi @dragino I open a new PR #305 for abp devices if it's right you can close this one.

**Pull request closed without merging**
