### PR TITLE
update-images

### PR DESCRIPTION
**Pull request by Jaime-Trinidad**
#### Summary

Update device makers images, format them, put them in transparent background for a better look in [https://www.thethingsnetwork.org/device-repository/](url)

#### Changes

- Transparent background
- Add device images
- Get a better format

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Review by johanstokking — APPROVED** [review]
The contents of the repo now grows from 156 to 209 MB. I'm not against it, but just be aware of this.

@mjamescompton @michalborkowski96 we should probably start looking into resizing images and serving them from a CDN.

**Comment by Jaime-Trinidad** [comment]
I agree, also plenty of devices have more than 1 image, this ones are not show in the console neither device repository page if we are not going to use them maybe they can be removed.

**Comment by mjamescompton** [comment]
@johanstokking  Hugo is resizing them for the website and @michalborkowski96 I believe already set up a cloudfront already, but because hugo is generating the new sizes so we are storing duplicates in the repo.

**Comment by michalborkowski96** [comment]
@mjamescompton 

These paths:

/device-repository/css/*
/device-repository/js/*
/device-repository/assets/*
/device-repository/devices/*.png
/device-repository/devices/*.jpg
/device-repository/devices/*.jpeg

are cached by CloudFront. Or at least should be. When in doubt, you can check particular image. It should have the `X-Cache` HTTP header with `Hit from CloudFront`. You first request can get `Miss from CloudFront`, but subsequent shouldn't.

**Pull request merged**
