### PR TITLE
Update vendor defs of Heltec

### PR DESCRIPTION
**Pull request by yanxiaolazy**
#### Summary
Update defs to replace RP001-1.0.2 with RP001-1.0.2-RevB

...

#### Changes

- ...
- ...

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Review by Jaime-Trinidad — APPROVED** [review]
Changes looks good in the profile files.

**Comment by yanxiaolazy** [comment]
> Changes looks good in the profile files.

Yes I do

**Comment by yanxiaolazy** [comment]
> Changes looks good in the profile files.

Hello, I don’t quite understand what you mean. The reason why I submitted this pr is because I received your proposal (https://github.com/TheThingsNetwork/lorawan-devices/pull/122#issuecomment-832413083) Replaced `RP001-1.0.2` with `RP001-1.0.2-RevB`. I did not change the original configuration including the profile file. I just changed the `regionalParametersVersion` parameter.

**Comment by Jaime-Trinidad** [comment]
> > Changes looks good in the profile files.
> 
> Hello, I don’t quite understand what you mean. The reason why I submitted this pr is because I received your proposal ([#122 (comment)](https://github.com/TheThingsNetwork/lorawan-devices/pull/122#issuecomment-832413083)) Replaced `RP001-1.0.2` with `RP001-1.0.2-RevB`. I did not change the original configuration including the profile file. I just changed the `regionalParametersVersion` parameter.

Hi @yanxiaolazy I just validate and give my approval so this can be merge, don´t worry nothing else have to be change.

**Review by johanstokking — APPROVED** [review]

**Comment by johanstokking** [comment]
Thanks @yanxiaolazy

**Pull request merged**
