### PR TITLE
Add RuiXingHengFang Network devices(RHF0M0E5,RHF0M003,RHF3MR01,RHF1S0…

### PR DESCRIPTION
**Pull request by lingtaoluorxhf**
…52,RHF1S213).

#### Summary

Add RuiXingHengFang Network devices

#### Changes

- Improve the vendor information of the RuiXingHengFang Network.(vendor/index.yaml)
- Add RuiXingHengFang Network devices(RHF0M0E5,RHF0M003,RHF3MR01,RHF1S052,RHF1S213)

### CODE REVIEW

**Comment by Jaime-Trinidad** [comment]
Hi @lingtaoluorxhf thanks for your submission, is it possible you can add decoder files and examples?

**Comment by lingtaoluorxhf** [comment]
Hi Jaime,

For some reasons, I couldn't add the decoder files and examples at present. I will add and perfect it in the future.

Best regards,
Lingtao



***@***.***
 
发件人： Jaime Trinidad
发送时间： 2021-05-18 19:55
收件人： TheThingsNetwork/lorawan-devices
抄送： lingtaoluorxhf; Mention
主题： Re: [TheThingsNetwork/lorawan-devices] Add RuiXingHengFang Network devices(RHF0M0E5,RHF0M003,RHF3MR01,RHF1S0… (#178)
Hi @lingtaoluorxhf thanks for your submission, is it possible you can add decoder files and examples?

**Comment by Jaime-Trinidad** [comment]
@lingtaoluorxhf please run: make validate fmt

**Comment by lingtaoluorxhf** [comment]
Hi @Jaime-Trinidad, when I run 'make validate fmt', I got a error message about the validate.js in line 216. But I have never modified this file.
image

**Comment by lingtaoluorxhf** [comment]
Hi @Jaime-Trinidad, What should I do next? Is this a bug about validate.js?

**Comment by Jaime-Trinidad** [comment]
> Hi @Jaime-Trinidad, What should I do next? Is this a bug about validate.js?

Please check you nodejs version this must be your problem, in README are versions you need.

**Comment by Jaime-Trinidad** [comment]
@lingtaoluorxhf  also please change rhf1s052 is too large max is 2000 x 2000

**Comment by lingtaoluorxhf** [comment]
@Jaime-Trinidad Thank you for your reminder. I have changed my nodejs version and image's size.

**Comment by lingtaoluorxhf** [comment]
Hi @Jaime-Trinidad , I'm sorry to cause you so much trouble. I had run 'make validate fmt' many times, but I always got a error message. I know that ‘make validate fmt’ is equivalent to ‘make validate’ and ‘make fmt’.

**Comment by lingtaoluorxhf** [comment]
@Jaime-Trinidad This is my node.js, npm and Go versions.
image

**Comment by lingtaoluorxhf** [comment]
@Jaime-Trinidad Now when I run 'make validate' or 'make validate fmt',  I got a same error message just like this. This is really weird.
image

**Review by Jaime-Trinidad — APPROVED** [review]
Decoder and examples will be added later, profiles, index and devices files looks fine

**Comment by Jaime-Trinidad** [comment]
@mjamescompton can you merge this PR?

**Pull request merged**
