### PR TITLE
Add Axioma water-meter

### PR DESCRIPTION
**Pull request by Jaime-Trinidad**
Add Axioma Water meter

Still missing examples and decoder files.

#### Changes

- ...
- ...

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Review by Jaime-Trinidad — COMMENTED** [review]
Axioma water-meter, device maker hasn't send example and decoder files

**Review by johanstokking — APPROVED** [review]
Can we get codecs?

**Comment by Jaime-Trinidad** [comment]
I am reaching Axioma for them.

**Comment by i3mSuperMan** [comment]
Hi @Jaime-Trinidad,

We see that the `axioma` brand is not shown in the TTS console after the new stack release i.e., `v3.13.2`. We believe this is due to a mismatch of id (i.e., `jsc-axioma`) [defined](https://github.com/TheThingsNetwork/lorawan-devices/blob/8cee0b8f690c5f473c3f729cb846ea8db37b3ecf/vendor/index.yaml#L988) in the index.yaml with the vendor folder naming convention `axioma`. Could you please check this?
Screenshot at 2021-06-18 21-43-06

**Pull request merged**
