### PR TITLE
vendorProfileId

### PR DESCRIPTION
**Pull request by Jaime-Trinidad**
#### Summary

Add unique `vendorProfileId` to The Things Product and The Things Industries devices #405 

#### Changes

- Add a unique `vendorProfileId` in each profile file, without repeating the Id
- The Id is a random number

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Review by KrishnaIyer — COMMENTED** [review]
@johanstokking: We are free to assign the `vendorProfileID` right? Should we follow some internal convention?
Just use linear numbers for each new profile?

**Review by johanstokking — COMMENTED** [review]
Indeed we're free to assign them. They're 16 bit. This is already enforced by the JSON schema validator.

I would indeed make them increasing and not jump to 868.

**Comment by KrishnaIyer** [comment]
> we can establish that 'vendorProfileId' should be filled linear instead of freely choice, what do you think?

 Ideally users can do what they want and we only check uniqueness but if that's too complicated to validate, then I guess it's ok to make it linear.

**Comment by johanstokking** [comment]
We can make this part of validation in CI. 

Can you file an issue @Jaime-Trinidad ?

**Comment by Jaime-Trinidad** [comment]
Yes I file an issue

**Pull request merged**
