### PR TITLE
Fix Elsys codec

### PR DESCRIPTION
**Pull request by Oliv4945**
#### Summary

Fix Elsys codec, it seems that the entrypoint was TTNv2 compatible instead of TTNv3

#### Changes

Change the entrypoint from `Decoder(bytes, port)` to `decodeUplink(input)`

@johanstokking is there a way for the validator to check that?

### CODE REVIEW

**Comment by johanstokking** [comment]
> @johanstokking is there a way for the validator to check that?

Yes, if there are examples declared, then the validator runs the codec.

It looks like examples are commented out, see for example: https://github.com/TheThingsNetwork/lorawan-devices/blob/47c65e28faefe86b90472ea2e89d5b891fd26963/vendor/elsys/elt-ultrasonic-codec.yaml

**Comment by johanstokking** [comment]
@Oliv4945 can you sign the CLA please? See https://cla-assistant.io/TheThingsNetwork/lorawan-devices?pullRequest=238

**Comment by Jaime-Trinidad** [comment]
@Oliv4945 thank you for the changes, examples work fine please sign CLA

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by Oliv4945** [comment]
@johanstokking  I did sign the CLA this morning but I just did it again

**Pull request merged**
