### PR TITLE
Moire Labs Slovakia P1AP and P1AT industrial devices

### PR DESCRIPTION
**Pull request by hecko**
#### Summary

Adds new vendor and two products

#### Changes

none

#### Notes for Reviewers

Submitted by device manufacturers employee (Marcel Hecko)

#### Release Notes

Add Moire Labs to vendors

### CODE REVIEW

**Review by johanstokking — COMMENTED** [review]
Thanks, can you add some codec examples?

**Comment by hecko** [comment]
> Thanks, can you add some codec examples?

@johanstokking added

**Comment by Jaime-Trinidad** [comment]
@hecko please run make fmt

**Comment by hecko** [comment]
@johanstokking @Jaime-Trinidad fmt done - thanks for noticing!

**Review by Jaime-Trinidad — APPROVED** [review]
Files looks fine

**Comment by hecko** [comment]
@johanstokking anything else I can do to have the merge approved? Ta!

**Comment by johanstokking** [comment]
@hecko thanks!

**Pull request merged**
