### PR TITLE
Add: add seeed lora e5 development boards

### PR DESCRIPTION
**Pull request by chenxixiya**
#### Summary

Add seeed lora e5 development boards

#### Changes

- ...
- ...

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Comment by chenxixiya** [comment]
Hello, I have signed the CLA. But there is an additional account "jianfengyu" shown up, which is the same email as "chenxixiya". Will that be a problem? I couldn't find a way to delete it. What should I do about it? Thanks

**Comment by Jaime-Trinidad** [comment]
> Hello, I have signed the CLA. But there is an additional account "jianfengyu" shown up, which is the same email as "chenxixiya". Will that be a problem? I couldn't find a way to delete it. What should I do about it? Thanks

yes it is strange let me check what can it be done

**Comment by chenxixiya** [comment]
Maybe I can start a new one and re-push it, to see what it happens.

**Comment by Jaime-Trinidad** [comment]
> Maybe I can start a new one and re-push it, to see what it happens.

Can you do that, to see if it is that.

**Pull request closed without merging**
