### PR TITLE
Update Tektelic Decoder + Manifests

### PR DESCRIPTION
**Pull request by jammiemil**
#### Summary
Update to Decoder to allow for all functionality to be recorded + new format + manifest updates to add additional info to the Device Repo

image

#### Changes

- Updated Decoder with Additional Metrics
- Updated Decoder format to match new standards

#### Notes for Reviewers
Unable to get this to validate locally as folders i havent made changes to fail to validate

### CODE REVIEW

**Comment by jammiemil** [comment]
Managed to get validate to run locally after sorting out my local environment, Golang version fun in WSL...

**Review by Jaime-Trinidad — APPROVED** [review]
Files look fine for me.

**Comment by Jaime-Trinidad** [comment]
> Managed to get validate to run locally after sorting out my local environment, Golang version fun in WSL...

yes, in README are instructions for WSL and how to update Golang, but as you said kind of fun, thanks for your submission @jammiemil

**Comment by kschiffer** [comment]
@jammiemil please rebase your branch on latest master, then we can merge.

**Comment by jammiemil** [comment]
> @jammiemil please rebase your branch on latest master, then we can merge.

@kschiffer I think I've done that correctly... This is my first time contributing to a public repo so be gentle with me :)

**Comment by Jaime-Trinidad** [comment]
@jammiemil yes is good, thank you very much!

**Pull request merged**
