### PR TITLE
added mcf88 devices

### PR DESCRIPTION
**Pull request by francozampicinini**
#### Summary

...

#### Changes

- ...
- ...

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Review by johanstokking — COMMENTED** [review]
@francozampicinini thanks very much

I renamed the `.yml` to `.yaml` so that the files are now correctly processed. Unfortunately we cannot support both yml and yaml as we might get conflicts then.

There are a few remaining issues, that are now also reported by CI:

1. The sensors can only be the ones listed. We can add new sensors without problem; let me know which ones you need. I think that "frequency" is a bit too broad: what is that, vibration frequency? Same for pulses; what kind of pulses are those?
2. Some keys are duplicate, i.e. `battery` is defined twice in files, and that makes it invalid YAML

Let me know if we can be of any assistance.

Please fetch and rebase the branch on your end; I updated on your remote.

cc @benolayinka

**Comment by francozampicinini** [comment]
> 1. The sensors can only be the ones listed. We can add new sensors without problem; let me know which ones you need. I think that "frequency" is a bit too broad: what is that, vibration frequency? Same for pulses; what kind of pulses are those?
> 2. Some keys are duplicate, i.e. `battery` is defined twice in files, and that makes it invalid YAML
> 

Everything it's clear.

Pulses means the device can count the cumulative number of digital pulses on the input.
Frequency means the device can measure the frequency of digital pulses on the input.

Thanks, 
Franco Zampicinini

**Comment by johanstokking** [comment]
@francozampicinini OK thanks for clarifying. We added `pulse count` and `pulse frequency` as valid sensors. Please rebase on latest `master`.

If there's anything you need help with, let us know.

**Comment by francozampicinini** [comment]
Closed, we will do another request with different files

**Comment by francozampicinini** [comment]
Hi, 

we closed the request and open a new one with the right sensors (#48), but still some errors I don’t understand.

 

Thanks, 

Franco Zampicinini

 

Da: Johan Stokking <notifications@github.com> 
Inviato: lunedì 11 gennaio 2021 12:08
A: TheThingsNetwork/lorawan-devices <lorawan-devices@noreply.github.com>
Cc: francozampicinini <franco.zampicinini@mcf88.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [TheThingsNetwork/lorawan-devices] added mcf88 devices (#42)

 

@francozampicinini <https://github.com/francozampicinini>  OK thanks for clarifying. We added pulse count and pulse frequency as valid sensors. Please rebase on latest master.

If there's anything you need help with, let us know.

**Pull request closed without merging**
