### PR TITLE
Add `motorized-valve` strega device

### PR DESCRIPTION
**Pull request by ymgupta**
#### Summary
Added `motorized-valve` Strega device as per the customer.

#### Changes
- Added `motorized-valve` to the Strega.
- Changed the regional parameter version of the devices to `RP001-1.0.2`
- Changed the supports Class C to `false`

### CODE REVIEW

**Review by Jaime-Trinidad — CHANGES_REQUESTED** [review]
Hello @ymgupta smart valve codec and image are empty files,  can you check this.

**Comment by surendar94** [comment]
> Hello @ymgupta smart valve codec and image are empty files, can you check this.

Dear @Jaime-Trinidad 

smart-valve

Is the coded file is empty?

**Comment by ymgupta** [comment]
Hi @Jaime-Trinidad,

In the [Files changed ](https://github.com/TheThingsNetwork/lorawan-devices/pull/283/files)tab, it is shown as an **Empty file**. But, when we open the file separately, we can see the file contents. We are not sure of the cause here. Could you please check once?
image
image

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by Jaime-Trinidad** [comment]
> Hi @Jaime-Trinidad,
> 
> In the [Files changed ](https://github.com/TheThingsNetwork/lorawan-devices/pull/283/files)tab, it is shown as an **Empty file**. But, when we open the file separately, we can see the file contents. We are not sure of the cause here. Could you please check once?
> image
> image

@ymgupta you are right.

**Pull request merged**
