### PR TITLE
Add cital device

### PR DESCRIPTION
**Pull request by gitahubbit**
#### Summary

Add cital device

...

#### Changes

- ...
- ...

#### Notes for Reviewers

validation failed for a decentlabs device: 
Error: Command failed: bin/runscript -codec-path "./vendor/decentlab/dl-5tm.js" -routine decodeUplink -input '{"fPort":1,"bytes":[2,2,59,0,2,12,96]}'

but the cital validation appears to have succeeded
cital: valid index
cital: lorasoil: valid
cital: lorasoil: EU863-870: profile cital/device-profile-eu valid
cital: lorasoil: US902-928: profile cital/device-profile-us valid
cital: lorasoil: AU915-928: profile cital/device-profile-au valid
cital: lorasoil: lorasoil.jpg image has correct extension

...

#### Release Notes

- ...

### CODE REVIEW

**Comment by Jaime-Trinidad** [comment]
Hi @gitahubbit please sign CLA

**Comment by Jaime-Trinidad** [comment]
@gitahubbit from `lorasoil-codec.yaml` please review the 3 examples, the input seems are not correct, from Example Payload 1:

`output {"data":{"ambient_humidity":10,"ambient_temperature":42.94,"latitude":0,"longitude":0,"soil_moisture":-88.72,"soil_temperature":43.43,"time_stamp":1659604659000}} does not match {"data":{"direction":"N","latitude":0,"longitude":0,"temperature":0,"moisture":0,"resistance":0}} `

**Comment by gitahubbit** [comment]
Hi Jamie,

I'll have a look into this.

Apart from the code - I signed the CLA already twice, but GutHub doesn't  
appear to indicate this correctly. It tells me that I haven't signed.  
Today I tried to sign again. Let's see if this time it worked out.

Best,
Andreas



On Sat, 06 Aug 2022 17:31:26 +0200, Jaime Trinidad  
***@***.***> wrote:

>
> @gitahubbit from lorasoil-codec.yaml please review the 3 examples, the  
> input seems are not correct, from Example Payload 1:
>
> output  
> {"data":>{"ambient_humidity":10,"ambient_temperature":42.94,"latitude":0,"longitude":0,"soil_moisture":-88.72,"soil_temperature":43.43,"time_stamp":1659604659000}}  
> >does not match  
> {"data":>{"direction":"N","latitude":0,"longitude":0,"temperature":0,"moisture":0,"resistance":0}}
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.



-- 
Andreas Senn
Bühlwiesenstrasse 10
8052 Zürich, Schweiz
+41 76 7000736

**Comment by Jaime-Trinidad** [comment]
Hi @gitahubbit the CLA I read and it might be the mail you register in, still pending the sign, I review the codec file, and there still some errors, the output of the payload using your decoder file is:

`{"data":{"ambient_humidity":10,"ambient_pressure":1014,"ambient_temperature":42.94,"battery":100,"latitude":0,"longitude":0,"soil_moisture":-88.72,"soil_temperature":43.43,"time_stamp":1659604659000}}`

It doesn't match with the data on the file, check soil resistance, humidity and ambient pressure are inverted, and decoder file is throwing a timestamp.

Take a look and let me know

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by Jaime-Trinidad** [comment]
Hi @gitahubbit everything is right now, I made some fixes, CLA is needed so I can merge it

**Comment by johanstokking** [comment]
@gitahubbit some of your commits were using the old email address, and the CLA is email address based. I'll reset the email address of these initial commits to match the email address of the other commits. That should work.

**Pull request merged**
