### PR TITLE
Added Hardware versions to all devices, updated payload decoder of elv-bm-trx1 to latest version

### PR DESCRIPTION
**Pull request by ELV-Elektronik-AG**
#### Summary

...

#### Changes

- added hardware version numbers to all devices
- updatet payload decoder of elv-bm-trx1 to latest version
- ...
- ...

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by Jaime-Trinidad** [comment]
@ELV-Elektronik-AG thanks for updates, please sign the CLA

**Comment by Jaime-Trinidad** [comment]
also please resolve the conflict in the PR

**Comment by ELV-Elektronik-AG** [comment]
Hi, i tried to sign the CLA but it still does not work

**Comment by ELV-Elektronik-AG** [comment]
I added the mail address to the latest commit but the CLA still doesn't seem to be working, can you do a force merge?

**Pull request merged**
