### PR TITLE
Create ts302

### PR DESCRIPTION
**Pull request by Charles-Milesight**
#### Summary

...

#### Changes

- ...
- ...

#### Checklist for Reviewers

- [ ] Title and description should be descriptive (Not just a serial number for example).
- [ ] `profileIDs` should not be `vendorID` and should be a unique value for every profile.
- [ ] All devices should be listed in the vendor's `index.yaml` file.
- [ ] Firmware versions can not be changed.
- [ ] At least 1 image per device and should be transparent.

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Review by LDannijs — COMMENTED** [review]
This file should be a javascript (.js) file as well.

**Review by LDannijs — APPROVED** [review]
Thanks, looks good! My colleague @Jaime-Trinidad will review it further. If you could in the meantime sign the CLA on both of your PRs that'd be great.

**Review by Jaime-Trinidad — APPROVED** [review]

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by Jaime-Trinidad** [comment]
Hi @Charles-Milesight everything is good, please sign the CLA

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by Jaime-Trinidad** [comment]
Hi @Charles-Milesight please sign the CLA so I can merge this PR

**Comment by Jaime-Trinidad** [comment]
Hi @Charles-Milesight any update here?

**Comment by Jaime-Trinidad** [comment]
Hi @Charles-Milesight

**Comment by Jaime-Trinidad** [comment]
Hi @Charles-Milesight please reopen the PR when you can sign the CLA, so I can merge this. Thank you

**Pull request closed without merging**
