### PR TITLE
talkpool: add a number of devices

### PR DESCRIPTION
**Pull request by jacquesg**
#### Summary

Add a number of Talkpool devices

#### Changes

Add a number of Talkpool devices

### CODE REVIEW

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by Jaime-Trinidad** [comment]
Hi @jacquesg thanks for your submission, there is an issue with the branch out-of-date maybe you need to pull the changes and run make validate fmt again and then push.

**Comment by jacquesg** [comment]
> Hi @jacquesg thanks for your submission, there is an issue with the branch out-of-date maybe you need to pull the changes and run make validate fmt again and then push.

I've done that, nothing changes locally for me?

**Comment by Jaime-Trinidad** [comment]
> > Hi @jacquesg thanks for your submission, there is an issue with the branch out-of-date maybe you need to pull the changes and run make validate fmt again and then push.
> 
> I've done that, nothing changes locally for me?

There is a problem with your branch and master one so is out-of-date, I create another PR with the files so it can be merged #314 you can close this PR.

**Comment by jacquesg** [comment]
> > > Hi @jacquesg thanks for your submission, there is an issue with the branch out-of-date maybe you need to pull the changes and run make validate fmt again and then push.
> > 
> > 
> > I've done that, nothing changes locally for me?
> 
> There is a problem with your branch and master one so is out-of-date, I create another PR with the files so it can be merged #314 you can close this PR.

Ok, maybe you wanted me to rebase it?

**Comment by Jaime-Trinidad** [comment]
Hi @jacquesg they are already merged by #314 I will close this one.

**Pull request closed without merging**
