### PR TITLE
Add: add SenseCAP version2.0 and one lora dev kit

### PR DESCRIPTION
**Pull request by BilltheWorld**
#### Summary

...

#### Changes

"Add: add SenseCAP version2.0 and one lora dev kit"

- ...
- ...

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Comment by BilltheWorld** [comment]
Hello, I have uploaded SenseCAP version2.0 and one lora dev kit here.

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by Jaime-Trinidad** [comment]
@BilltheWorld there are some conflicts as you also modify Noah files, please solve them.

**Comment by BilltheWorld** [comment]
Hello, I changed the files and the validate seems to be ok. But there is a format problem and it said I should run the Prettier. I installed the Prettier and run it then lots of js. files have been changed. I'm afraid that I might cause some error so I didn't upload them. What should I do?
Thanks.

**Comment by BilltheWorld** [comment]
Hello, I have fixed the files and all seems to be OK. :D

**Pull request merged**
