### PR TITLE
Added Embit Links to the products

### PR DESCRIPTION
**Pull request by andguaEmbit**
#### Summary

...

#### Changes

- ...
- ...

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Comment by johanstokking** [comment]
@andguaEmbit I have a really hard time with the casing; Embit vs embit. It has to be `embit` (lowercase). Are you on Windows? Or are you using a case sensitive file system?

**Comment by johanstokking** [comment]
@andguaEmbit any update here?

**Comment by Jaime-Trinidad** [comment]
Hi @andguaEmbit can you help us updating. Thanks

**Comment by Jaime-Trinidad** [comment]
This Embit devices are already in Device Repository, I close this PR.

**Pull request closed without merging**
