### PR TITLE
Fixes in ioTracker 3 uplink decoder

### PR DESCRIPTION
**Pull request by Bertje**
#### Summary
Fixes in ioTracker 3 uplink decoder

#### Changes
- Fix in GPS uplink parser.
- TTN codestyle and notation alignment fixes.

### CODE REVIEW

**Comment by Jaime-Trinidad** [comment]
@Bertje Hi for the change, can you rebase the PR please so I can approve the review.

**Comment by Bertje** [comment]
Done.

**Comment by Jaime-Trinidad** [comment]
@Bertje I merge some PRs, so please rebase again so I merge it once you rebase it. Thanks

**Comment by Bertje** [comment]
Done @Jaime-Trinidad

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by Jaime-Trinidad** [comment]
Thanks @Bertje

**Pull request merged**
