### PR TITLE
feat: Add n-fuse STx device familiy

### PR DESCRIPTION
**Pull request by vanthome**
#### Summary

n-fuse STx devices

#### Changes

Initial add

### CODE REVIEW

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by Jaime-Trinidad** [comment]
Hi @vanthome thanks for adding your devices, please run `make validate fmt` and push again your PR

**Comment by vanthome** [comment]
Hi @Jaime-Trinidad it fails here:

```
n-fuse: sta: EU863-870: payload codec sta-codec valid
n-fuse: ste: EU863-870: payload codec ste-codec valid
n-fuse: stx: EU863-870: payload codec stx-codec valid
laird: rs1xx-ext-temp-rtd-sensor: EU863-870: payload codec rs1xx-ext-temp-rtd-sensor-codec invalid
Error: Command failed: bin/runscript -codec-path "./vendor/laird/rs1xx-ext-temp-rtd-sensor.js" -routine decodeDownlink -input '{"fPort":1,"bytes":[5,4,1,244]}'
```

Which is not our sensor, right?

**Comment by LDannijs** [comment]
Hello @vanthome I will be able to help you along as well.
Could you try running `make validate fmt -i`? Our validation has some issues but its in the process of getting fixed.

**Comment by vanthome** [comment]
@LDannijs. amother device is acting up not ours:

```
tip: sinus85: EU863-870: payload codec sinus85-codec valid
n-fuse: sta: EU863-870: payload codec sta-codec valid
n-fuse: ste: EU863-870: payload codec ste-codec valid
n-fuse: stx: EU863-870: payload codec stx-codec valid
laird: rs1xx-ext-temp-rtd-sensor: EU863-870: payload codec rs1xx-ext-temp-rtd-sensor-codec invalid
Error: Command failed: bin/runscript -codec-path "./vendor/laird/rs1xx-ext-temp-rtd-sensor.js" -routine decodeDownlink -input '{"fPort":1,"bytes":[5,4,1,244]}'
/bin/sh: 1: bin/runscript: not found

    at ChildProcess.exithandler (node:child_process:412:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:313:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: `bin/runscript -codec-path "./vendor/laird/rs1xx-ext-temp-rtd-sensor.js" -routine decodeDownlink -input '{"fPort":1,"bytes":[5,4,1,244]}'`
}
make: [Makefile:37: validate] Error 1 (ignored)
npm run format

**Comment by LDannijs** [comment]
How strange, i am not running into that issue when opening your fork. I am able to run `make validate fmt -i` without error. Since i cannot push changes I'll have @Jaime-Trinidad look at it further.

**Comment by vanthome** [comment]
@Jaime-Trinidad can you please check this?

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by Jaime-Trinidad** [comment]
Hi @vanthome everything looks good just run `make validate fmt`

**Comment by vanthome** [comment]
@Jaime-Trinidad I did that and it worked now. I have updated the branch. Can you please merge it then?

**Comment by vanthome** [comment]
@Jaime-Trinidad many many thanks!!
How long will it take until I can actually select the device from the TTN console?

**Comment by LDannijs** [comment]
@vanthome should be with the next release, which is scheduled to be `v3.30.0`, around end of march/begin of april.

**Pull request merged**
