### PR TITLE
add yo-people-counter and changed pictures for yo devices,modified ya…

### PR DESCRIPTION
**Pull request by yosensi**
…ml files

Change-Id: I2d480b7b9fca37b39fa4a75aa96d623c2849d698

#### Summary

added yo-people-counter device 
#### Changes

- changed and added pictures for all devices (name of the pictures are yo-device-2.png) profile except yo-refrigerant and yo pure pro
- made some changes in profile modbus, pulse, changed description for yo-pulse,

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Comment by yosensi** [comment]
hello I did npx prettier --check schema.json "vendor/**/*.yaml" "bin/**/*.js" in my file but there was no error. Why in checks error appeared?

**Comment by yosensi** [comment]
Hello I created new pull request but from your website our devices dissapered. Can you explain what happened?

**Comment by Jaime-Trinidad** [comment]
Hi @yosensi do we still need this PR? let me know or close it, I send you where you can see the images.

**Comment by yosensi** [comment]
Yes we still need to process this pull request. I added new devices to vendor list in yosensi and I want to display it on your website.

**Comment by yosensi** [comment]
@Jaime-Trinidad hello did someone checked thi PR?

**Pull request closed without merging**
