### PR TITLE
Update device descriptions

### PR DESCRIPTION
**Pull request by pradeeka7**
#### Summary

... Updating device descriptions with sensor types and optimized for SEO.

#### Changes

- Used sensor types as keywords throughout the descriptions.
- ...

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Review by johanstokking — APPROVED** [review]

**Comment by johanstokking** [comment]
@pradeeka7 thanks a lot. Hard work I can tell.

Please run `make fmt` locally and push again to this branch.

**Review by Jaime-Trinidad — APPROVED** [review]
@pradeeka7 Thank you!

**Comment by Jaime-Trinidad** [comment]
@pradeeka7 you run make fmt?

**Comment by pradeeka7** [comment]
@Jaime-Trinidad  - Yes, I just run the command 'make fmt'. It doesn't show any issue.

However, it gives this error for the command 'make validate'

```
elsys: ems-desk: EU863-870: payload codec ems-desk-codec valid
netvox: r718ck: EU863-870: payload codec r718ck-codec invalid
Error: Command failed: bin/runscript -codec-path "./vendor/netvox/payload/r718cj_ck_ct_cr_ce_r718b.js" -routine decodeDownlink -input '{"fPort":7,"bytes":[2,145,0,0,0,0,0,0,0,0,0]}'
/bin/sh: 1: bin/runscript: not found

    at ChildProcess.exithandler (node:child_process:326:12)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Socket.<anonymous> (node:internal/child_process:453:11)
    at Socket.emit (node:events:394:28)
    at Pipe.<anonymous> (node:net:661:12) {
  killed: false,
  code: 127,
  signal: null,
  cmd: `bin/runscript -codec-path "./vendor/netvox/payload/r718cj_ck_ct_cr_ce_r718b.js" -routine decodeDownlink -input '{"fPort":7,"bytes":[2,145,0,0,0,0,0,0,0,0,0]}'`
}
make: *** [Makefile:37: validate] Error 1
pradeeka@DESKTOP-7O34TPN:~/lorawan-devices$
```

**Comment by pradeeka7** [comment]
> thanks a lot. Hard work I can tell.

@johanstokking - You are welcome!

**Comment by johanstokking** [comment]
@pradeeka7 please run `make deps` first, see also the README here. I managed to format the files in your branch and will merge when CI passes. Thanks again!

**Comment by pradeeka7** [comment]
@johanstokking

> I managed to format the files

Thanks for formatting those files.

> please run `make deps` first

I am getting this error:

```
...
...
go: finding github.com/golang/protobuf v1.5.1
go: finding github.com/gogo/protobuf v1.3.2
go: finding google.golang.org/genproto v0.0.0-20210429181445-86c259c2b4ab
go: finding google.golang.org/grpc v1.37.0
**build github.com/TheThingsNetwork/lorawan-devices/tools/runscript: cannot find module for path hash/maphash
make: *** [Makefile:28: deps] Error 1**
```

after that the go.mod file has updated like this:

image

**Pull request merged**
