### PR TITLE
Add Sensedge devices

### PR DESCRIPTION
**Pull request by sensedgeco**
#### Summary

Add senstick-pro and senstick-pure

#### Changes

- ...
- ...

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Comment by sensedgeco** [comment]
A boš ti to podpisal?

T
-- 

Dr.* Tomaz** Suklje*, Mech.Eng.
CEO & Co-Founder

Sensedge d.o.o.,Podbreznik 15, SI-8000 Novo mesto
www.sensedge.co
www.microclimate.network


V V čet., 14. jan. 2021 ob 15:18 je oseba CLAassistant <
notifications@github.com> napisala:

**Comment by johanstokking** [comment]
Thanks Tomaz, I made some changes, see 3417eb1

Please verify the numeric versions (has to be an integer) and the sensors.

If you have additional sensors that need to be added, please open a pull request for the sensors: https://github.com/lorawan-schema/draft-devices/blob/e8cb2828bce13ad59511427f26bd0fae62dbb0ea/schema.json#L787-L830

**Review by johanstokking — APPROVED** [review]
Waiting for @sensedgeco to confirm that it can be merged like this

**Comment by sensedgeco** [comment]
Hi Johan,

We are confirming the changes.

Br,
Luka

**Pull request merged**
