### PR TITLE
Add HelTec devices

### PR DESCRIPTION
**Pull request by yanxiaolazy**
#### Summary

Add HelTec devices

#### Changes

- Add devices
    - CubeCell-GPS-6502
    - CubeCell-Dev-Board
    - CubeCell-Dev-Board Plus
    - CubeCell-1/2 AA Node
    - CubeCell–Capsule Sensor
    - CubeCell-Capsule Solar Sensor
    - CubeCell–Module
    - CubeCell-Module Plus
    - WiFi LoRa 32 (V2)
    - Wireless Stick (Gecko Board)
    - Wireless Stick Lite (Panda Board)
    - Wireless Shell
    - LoRa Kit 151
    - LoRa Node 151
    - Turtle Board

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Review by johanstokking — APPROVED** [review]

**Comment by johanstokking** [comment]
Thanks @yanxiaolazy !

If you want to add codecs and examples later, that would be highly appreciated.

**Comment by Heltec-Aaron-Lee** [comment]
Hi @johanstokking 

The devices submitted this time are all development boards, and users may connect various sensors to the development boards, so a general decoder is not added. We will add decoders to future application-level products.

BTW. Another quick question: when will these submitted devices be included in the `lorawan-stack` image? Or do we need to perform other operations to make the device appear in the TTS device list?
image

**Comment by johanstokking** [comment]
> The devices submitted this time are all development boards, and users may connect various sensors to the development boards, so a general decoder is not added. We will add decoders to future application-level products.

Understood.

What you could do for development board, is include firmware versions for examples (assuming that you provide example firmwares). We did a similar thing with The Things Uno quickstart, see https://github.com/TheThingsNetwork/lorawan-devices/blob/cb0f1881048645f9075f5cd1ec4ffd3fd6fe76d1/vendor/the-things-products/the-things-uno.yaml

> BTW. Another quick question: when will these submitted devices be included in the `lorawan-stack` image? Or do we need to perform other operations to make the device appear in the TTS device list?
> image

When we roll a new release, see release planning here: https://github.com/TheThingsNetwork/lorawan-stack/milestones?direction=asc&sort=due_date. When a release is done, it usually takes a few days for it to be deployed to our production environments.

We're still working on a way to automatically reload the device repository.

**Comment by Bwooce** [comment]
Hi @Heltec-Aaron-Lee these defs need to move to use RP001-1.0.2-RevB rather than RP001-1.0.2 inside them -- using RevA means OTAA doesn't work (at least for AU915 OTAA).  It's quite frustrating to debug that, works first time when moved to RevB.

Do you want a pull request? It really needs to come from you for @johanstokking to treat it as legit, I wouldn't trust me :-)

**Pull request merged**
