### PR TITLE
Add r718pa,r718pa4,r718pb,rp02,r718n3 support

### PR DESCRIPTION
**Pull request by netvox-tech**
Add r718pa,r718pa4,r718pb,rp02,r718n3 support

### CODE REVIEW

**Comment by Jaime-Trinidad** [comment]
hi @netvox-tech this PR is the same as #717 which one is the one to review?

**Review by LDannijs — COMMENTED** [review]
Could you please add images for the devices as well?

**Comment by netvox-tech** [comment]
Dear Sir,

please review #718. Thank you.


On Thu, 07 Dec 2023 04:31:35 -0800, Jaime Trinidad wrote
> hi @netvox-tech this PR is the same as #717 which one is the one to review?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/TheThingsNetwork/lorawan-devices/pull/718#issuecomment-1845261968
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>
> -- 
> This message has been scanned for viruses and
> dangerous content by MailScanner, and is
> believed to be clean.


--
Regards......your name  (http://www.netvox.com.tw)


-- 
This message has been scanned for viruses and
dangerous content by MailScanner, and is
believed to be clean.

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by Jaime-Trinidad** [comment]
@netvox-tech please add images of the devices, when we merge it the information will be deployed https://www.thethingsnetwork.org/device-repository/ without background please

**Comment by Jaime-Trinidad** [comment]
@netvox-tech any update?

**Comment by LDannijs** [comment]
@netvox-tech any update here?

**Comment by netvox-tech** [comment]
You said it was approved, then you mentioned missing images, and finally you mentioned conflicts. So what was the final situation?

**Comment by LDannijs** [comment]
The situation is that it's missing images. Please add those and then it should be good.

**Comment by LDannijs** [comment]
@netvox-tech Could you please still add the images so that we can approve of this PR?

**Comment by netvox-tech** [comment]
@LDannijs 

We had added images for these devices as below pull request.
image
Would you please tell us which one we missed?

**Comment by LDannijs** [comment]
@netvox-tech I had not expected you to make a seperate PR for the images. 

I see all the files from this PR are in the DR now, so can we close this one?

**Comment by LDannijs** [comment]
From what i can see these files are added in the repo with the other PRs, closing this.

**Pull request closed without merging**
