### PR TITLE
Add yo-pure-pro

### PR DESCRIPTION
**Pull request by konradzimek1**
Change-Id: I65fbb04f56f79b4af33fdaef71a8f908387fec95

#### Summary

add yosesni folder to vendor 
Add yo-pure-pro 
#### Changes

- ...
- ...

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Comment by Jaime-Trinidad** [comment]
Hi @konradzimek1 please sign CLA

**Comment by konradzimek1** [comment]
Hi @Jaime-Trinidad , I have to merge the same changes but from diffrent account. You can cancell this commit to device repo.

**Comment by Jaime-Trinidad** [comment]
@

**Comment by Jaime-Trinidad** [comment]
@konradzimek1 ok I close this PR

**Pull request closed without merging**
