### PR TITLE
Add WILSEN.sonic.level device

### PR DESCRIPTION
**Pull request by djang0402**
#### Summary

Add WILSEN.sonic.level device

#### Changes

- Add yaml files for WILSEN.sonic.level device
- Add an image file of WILSEN.sonic device

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by djang0402** [comment]
Hi, is there anything else I need to process `license/cla`?

**Comment by djang0402** [comment]
Hi, when will this commits be merged? Do I need to do something more to merge this?

**Comment by johanstokking** [comment]
@djang0402 apologies for getting back late.
You should also list this new vendor in `vendor/index.yaml`. That should be it.

**Comment by johanstokking** [comment]
Sorry, my bad!

**Pull request merged**
