### PR TITLE
Changed KU Leuven Dramco Uno LoRaWAN versions

### PR DESCRIPTION
**Pull request by guusleenders**
#### Summary

Changed the KU Leuven Dramco Uno LoRaWAN versions. 

#### Changes

- Changed macVersion to 1.0.3
- Changed regionalParametersVersion to  RP001-1.0.3-RevA

### CODE REVIEW

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by Jaime-Trinidad** [comment]
Hi @guusleenders please rebase so i can merge it. Thanks

**Comment by Jaime-Trinidad** [comment]
Hi @guusleenders can you please rebase your branch please, sorry for this but is protected and I can't update it.

**Comment by johanstokking** [comment]
@guusleenders you need to update the branch. We can't do it because we can't write to your fork.

**Comment by Jaime-Trinidad** [comment]
@guusleenders any update here, so we can merge this

**Comment by Jaime-Trinidad** [comment]
Hi @guusleenders please update the PR

**Pull request closed without merging**
