### PR TITLE
Add Teneo IoT devices

### PR DESCRIPTION
**Pull request by TeneoIoT**
#### Summary

Added the CO2 stoplicht and filling degree sensor for Teneo IoT.

Please note that the make validate command has failed for me while validating the file ./vendor/the-things-products/the-things-uno-quickstart.js. Due to this error i could not verify locally, which is why there are so many commits.

### CODE REVIEW

**Comment by johanstokking** [comment]
Thanks @TeneoIoT! The error that I'm seeing is:

```
./vendor/teneo-iot/filling-degree-sensor.js:decodeUplink: 3.3v battery, error measuring distance has correct output
teneo-iot: filling-degree-sensor: EU863-870: payload codec filling-degree-sensor-codec invalid
./vendor/teneo-iot/filling-degree-sensor.js:decodeUplink: output {"data":{"battery":3.4,"charging":false,"sensorType":"fillrate","settingsAllowed":true}} does not match {"data":{"battery":3.4,"charging":false,"sensorType":"fillrate","settingsAllowed":true,"distance":120}}
```

That looks simply like `distance` is not in the example output data. When I do that locally, I'm getting the next error:

```
./vendor/teneo-iot/filling-degree-sensor.js:decodeUplink: 3.3v battery, error measuring distance has correct output
teneo-iot: filling-degree-sensor: EU863-870: payload codec filling-degree-sensor-codec invalid
./vendor/teneo-iot/filling-degree-sensor.js:decodeUplink: output {"data":{"battery":3.4,"charging":false,"sensorType":"fillrate","settingsAllowed":true}} does not match {"data":{"battery":3.4,"charging":false,"sensorType":"fillrate","settingsAllowed":true,"distance":120}}
```

This looks like wrong input or wrong decoding.

**Comment by johanstokking** [comment]
@TeneoIoT for your convenience, I rebased on `master` and formatted files. Please fetch and rebase on your end, or reset hard.

**Comment by TeneoIoT** [comment]
@johanstokking We can't find a reason for a not matching output of the decoded uplink, error:
`./vendor/teneo-iot/filling-degree-sensor.js:decodeUplink: output {"data":{"battery":3.4,"charging":false,"sensorType":"fillrate","settingsAllowed":true}} does not match {"data":{"battery":3.4,"charging":false,"sensorType":"fillrate","settingsAllowed":true,"distance":120}}`
When we test the decoder outside of this repo's context it all works as expected, although it won't pass through the validation script here.

**Comment by benolayinka** [comment]
> @johanstokking We can't find a reason for a not matching output of the decoded uplink, error:
> `./vendor/teneo-iot/filling-degree-sensor.js:decodeUplink: output {"data":{"battery":3.4,"charging":false,"sensorType":"fillrate","settingsAllowed":true}} does not match {"data":{"battery":3.4,"charging":false,"sensorType":"fillrate","settingsAllowed":true,"distance":120}}`
> When we test the decoder outside of this repo's context it all works as expected, although it won't pass through the validation script here.

It looks like the `distance` field is missing.

**Comment by johanstokking** [comment]
You can easily test locally with `make validate`

Let us know if you need further help

**Comment by benolayinka** [comment]
Hi @TeneoIoT, I double checked your codecs and the only issue is that `input.port` in your decoders should be `input.fPort` -> https://github.com/TheThingsNetwork/lorawan-devices/pull/56/files#diff-092f60318a87766fedc4ffea29c50b46a4e20fc2571f18ed0338b9009199e992R6

Fixing this produces the correct decoder results on my end.

**Comment by johanstokking** [comment]
Thanks @TeneoIoT. I fixed two things:

1. Formatting and rename `port` to `fPort`: https://github.com/TheThingsNetwork/lorawan-devices/pull/56/commits/8000cff03f02ddd125abfcf86da2c5a7c6baa5e8
2. The codecs: https://github.com/TheThingsNetwork/lorawan-devices/pull/56/commits/8000cff03f02ddd125abfcf86da2c5a7c6baa5e8

Let me know if this looks good to you, and then it's ready to go

**Comment by TeneoIoT** [comment]
> Thanks @TeneoIoT. I fixed two things:
> 
> 1. Formatting and rename `port` to `fPort`: [262483e](https://github.com/TheThingsNetwork/lorawan-devices/commit/262483e341cdce65b01a244c97245caa2790025d)
> 2. The codecs: [8000cff](https://github.com/TheThingsNetwork/lorawan-devices/commit/8000cff03f02ddd125abfcf86da2c5a7c6baa5e8)
> 
> Let me know if this looks good to you, and then it's ready to go

Hello, I was actually validating it myself just 10 minutes ago and these were the bugs that prevented me from passing the validation. So yes, this is how it is supposed to look. It can be merged like this. Thanks for the support!

**Review by johanstokking — APPROVED** [review]

**Pull request merged**
