### PR TITLE
Update WSL README.md

### PR DESCRIPTION
**Pull request by Jaime-Trinidad**
#### Summary

Improve WSL installation guide for Windows users #276 

#### Changes

- Add a more detailed guide for installing dependencies in windows
- ...

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Comment by Jaime-Trinidad** [comment]
@benolayinka can you take a look at this update

**Review by johanstokking — COMMENTED** [review]
I really don't think we should be copying these instructions in in our README. Installing Node and Go under WSL should be documented properly somewhere right?

**Review by johanstokking — COMMENTED** [review]
We're now on Go 1.18.x

But why not refer to other documentation, like https://ao.ms/how-to-install-golang-on-wsl-wsl2/ ?

**Comment by Jaime-Trinidad** [comment]
Last months the repository has been very active by makers or users adding devices until now we haven't got any comment on how to run it on Windows, I think as the information is now working for users, I will close this PR.

**Pull request closed without merging**
