### PR TITLE
Adding KS Technologies Impulse KST5420 - Proof of Coverage Test Tool

### PR DESCRIPTION
**Pull request by Devin-Saavedra**
#### Summary
Adding KS Technologies Impulse KST5420 - Proof of Coverage Test Tool

#### Checklist for Reviewers

- [X] Title and description should be descriptive (Not just a serial number for example).
- [X] `vendorProfileID` should not be `vendorID`.
- [X] All devices should be listed in the vendor's `index.yaml` file.
- [X] At least 1 image per device and should be transparent.

#### Notes for Reviewers
@LDannijs after updating the fork to the latest I am now seeing this error after running `make validate fmt`:
```
ks-technologies: valid index
ks-technologies: kst5420: valid
ks-technologies: kst5420: kst5420.png image has correct extension
node:fs:590
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open './vendor/800/kst5420-profile.yaml'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at /Users/devin/Desktop/Projects/lorawan-devices/bin/validate.js:280:42
    at Array.forEach (<anonymous>)
    at /Users/devin/Desktop/Projects/lorawan-devices/bin/validate.js:272:39
    at Array.forEach (<anonymous>)
    at /Users/devin/Desktop/Projects/lorawan-devices/bin/validate.js:254:34
    at Array.forEach (<anonymous>)
    at /Users/devin/Desktop/Projects/lorawan-devices/bin/validate.js:244:23
    at FSReqCallback.oncomplete (node:fs:203:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './vendor/800/kst5420-profile.yaml'
}
make: *** [validate] Error 1
```

That error makes it seem as if the `kst5420-profile.yaml` does not exit, but it does. Sorry if I am missing something here.

### CODE REVIEW

**Comment by LDannijs** [comment]
I am also having trouble with the validation hanging on a milesight file.. running `make validate fmt -i` however does work for me and reveals some prettier issues. Maybe try that command again.

**Comment by Devin-Saavedra** [comment]
@LDannijs I ran `make validate fmt -i` and I still only see this error `Error: ENOENT: no such file or directory, open './vendor/800/kst5420-profile.yaml'` Which it does exist. 
Once the `npm run format` hits with that above command I can see `vendor/ks-technologies/kst5420-profile.yamlvendor/ks-technologies/kst5420-profile.yaml 1ms` being listed with no errors. 

I'm just confused here. If the file it thinks is missing is not missing, how can we resolve this?

**Comment by LDannijs** [comment]
This is getting out of the scope of my knowledge at the moment, and i do not have write privileges so i think it would be best to wait for my colleague @Jaime-Trinidad to help you. I apologize for the hiccups.

**Comment by Devin-Saavedra** [comment]
Hey @LDannijs no worries, I appreciate all the help that you have given me thus far! 
I will wait for @Jaime-Trinidad's help now.

**Comment by Jaime-Trinidad** [comment]
Hi @Devin-Saavedra as you have a protected branch it makes it difficult sometimes to review, this means for example I can update the branch, I need you to do it but every time we merge another PR you will need to update this so we can continue testing (if we haven't finished the fixes).

can you update the branch and pull the latest, this kind of issue of ENOENT was fixed with some of the latest changes we made.

Please let me know so we can find the problem

**Comment by Devin-Saavedra** [comment]
Hey @Jaime-Trinidad I didn't think I have any protection rules set here, but I will double-check that. 
I will update the branch and pull the latest and check to see if that ENOENT error is fixed.
Thanks!

**Comment by Devin-Saavedra** [comment]
Hey @Jaime-Trinidad 
Branch is updated and the latest is pulled. There are no branch protection rules set.
After updating I re-ran the `make validate fmt` and am still getting the following error:
```
ks-technologies: valid index
ks-technologies: kst5420: valid
ks-technologies: kst5420: kst5420.png image has correct extension
node:fs:590
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open './vendor/800/kst5420-profile.yaml'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at /Users/devin/Desktop/Projects/lorawan-devices/bin/validate.js:280:42
    at Array.forEach (<anonymous>)
    at /Users/devin/Desktop/Projects/lorawan-devices/bin/validate.js:272:39
    at Array.forEach (<anonymous>)
    at /Users/devin/Desktop/Projects/lorawan-devices/bin/validate.js:254:34
    at Array.forEach (<anonymous>)
    at /Users/devin/Desktop/Projects/lorawan-devices/bin/validate.js:244:23
    at FSReqCallback.oncomplete (node:fs:203:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './vendor/800/kst5420-profile.yaml'
}
```

Let me know what else I can do here to help you troubleshoot this issue.
Thank you!

**Comment by Jaime-Trinidad** [comment]
Hi @Devin-Saavedra I will close this PR, I create #750 and fixed the issues, also codec examples need to be reviewed and decoder file can be improved.

**Pull request closed without merging**
