### PR TITLE
add elv-bm-trx1

### PR DESCRIPTION
**Pull request by ELV-Elektronik-AG**
#### Summary

...

#### Changes
 add elv-bm-trx1 (ELV experimental platform for LoRaWAN) 

- ...
- ...

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Comment by Jaime-Trinidad** [comment]
Hi @ELV-Elektronik-AG please sign the CLA

**Comment by ELV-Elektronik-AG** [comment]
I have already signed the CLA, but it still shows up as a not signed jet

**Comment by ELV-Elektronik-AG** [comment]
Hello, I have signed the CLA, and checked this several times. Is there anything else i need to do, in order that you merge the changes?

**Comment by Jaime-Trinidad** [comment]
Hi @ELV-Elektronik-AG 
GitHub and CLA assistant so can not recognize you as a committer. The only thing you need to do is to add the e-mail address you used in your commit to your GitHub account, try to see if it's that.

**Comment by Jaime-Trinidad** [comment]
Hi @ELV-Elektronik-AG any update with the CLA?

**Comment by ELV-Elektronik-AG** [comment]
Hello @Jaime-Trinidad, i pushed the latest chnages to this fork with the email set in the git settings. I also tried to sign the CLA multiple times but the status does not change to "signed". It seems like i'm still missing something

**Comment by johanstokking** [comment]
> Hello @Jaime-Trinidad, i pushed the latest chnages to this fork with the email set in the git settings. I also tried to sign the CLA multiple times but the status does not change to "signed". It seems like i'm still missing something

I had to reset the author of one of the commits, which as a local domain email address. The CLA check now passes.

**Review by johanstokking — APPROVED** [review]
Looks perfect, thanks

**Pull request merged**
