### PR TITLE
synetica: add support for enlink Zone sensors

### PR DESCRIPTION
**Pull request by jacquesg**
#### Summary

Adds support for Synetica enlink Zone sensors.

#### Changes

Adds support for Synetica enlink Zone sensors.

### CODE REVIEW

**Comment by Jaime-Trinidad** [comment]
Hi @jacquesg this PR also is having the problem with out-of-date with the base branch, also I can make any change because is protected, can you check on your side to see what is going on? Also I can create a new PR as the others. Let me know so we can merge this and #310 #309

**Comment by jacquesg** [comment]
Rebased.

**Comment by jacquesg** [comment]
The CI system seems to be broken, unable to install the npm dependencies.

**Comment by Jaime-Trinidad** [comment]
Hi @jacquesg now dependencies work fine, can you rebase this PR so I can run it and merge it. Thank you.

**Pull request closed without merging**
