### PR TITLE
Add SENSO8 LoRaWAN sensors

### PR DESCRIPTION
**Pull request by arthur-arwin**
#### Summary

Add SENSO8 LoRaWAN sensors, including temperature/humidity, water leak and open close contact sensor.

#### Changes

- Add LRS20100 temperature/humidity sensor
- Add LRS20310 water leak sensor
- Add LRS20600 open close sensor
- Add EU868, US915 and AS923 profiles for the sensors

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Comment by arthur-arwin** [comment]
> 

@Jaime-Trinidad I've made the changes.

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by arthur-arwin** [comment]
@Jaime-Trinidad any further action required on our side?

**Comment by arthur-arwin** [comment]
> @arthur-arwin can you resolve the conflicts in your files please

@Jaime-Trinidad I've resolved the conflicts. Any further action required from me?

**Comment by Jaime-Trinidad** [comment]
Hi @arthur-arwin there is still one error in `lrs20100-codec.yaml` `dataUploadInterval` output is `3840` you can check it running
`bin/runscript -codec-path "./vendor/arwin-technology/lrs20100.js" -routine decodeUplink -input '{"fPort":12,"bytes":[1,0,15,0,1]}' `

**Comment by arthur-arwin** [comment]
> Hi @arthur-arwin there is still one error in `lrs20100-codec.yaml` `dataUploadInterval` output is `3840` you can check it running `bin/runscript -codec-path "./vendor/arwin-technology/lrs20100.js" -routine decodeUplink -input '{"fPort":12,"bytes":[1,0,15,0,1]}' `

I've fixed the error and passed 'make validate'. Thanks!

**Comment by arthur-arwin** [comment]
> Hi @arthur-arwin there is still one error in `lrs20100-codec.yaml` `dataUploadInterval` output is `3840` you can check it running `bin/runscript -codec-path "./vendor/arwin-technology/lrs20100.js" -routine decodeUplink -input '{"fPort":12,"bytes":[1,0,15,0,1]}' `

@Jaime-Trinidad I've fixed the error and passed 'make validate'. Thanks!

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by arthur-arwin** [comment]
@Jaime-Trinidad We have fixed the codes blocking the checks. Any further action required from us?

**Comment by arthur-arwin** [comment]
No idea how to resolve and cannot proceed with the merge.

**Pull request closed without merging**
