### PR TITLE
Add smart-parks device

### PR DESCRIPTION
**Pull request by tjvandam**
#### Summary

Add smart-parks device

#### Changes

- ...
- ...

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by Jaime-Trinidad** [comment]
@tjvandam thanks for fixing your files, they continue throwing an error, I make some little changes but I can not commit them, please run make validate fmt.

**Comment by tjvandam** [comment]
Please help me with some clues here, as I do not understand why the validation is failing on my commit. It is failing on the line which is for the Elsys ELT sensor not on the files I have added / changed --> Error: Process completed with exit code 2. Why is it failing?

**Comment by Jaime-Trinidad** [comment]
are you on windows or which OS? 
Try `make deps` then `make validate` it works? or continue Error?

**Comment by tjvandam** [comment]
I am using windows and the `make validate` and `make validate fmt` keep on failing, but not on my contributions. Now `make validate fmt` failed with: 

> Error: Command failed: bin/validate-image ./vendor/decentlab/dl-mbx-5.jpg
> 'bin' is not recognized as an internal or external command,
> operable program or batch file.

What can I do?

**Comment by tjvandam** [comment]
Also if I run 'make deps' I get an error I can not resolve:

> npm install
> audited 76 packages in 0.71s
> 
> 4 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
> 
> pushd ./tools/runscript && go install . && popd
> The syntax of the command is incorrect.

**Comment by Jaime-Trinidad** [comment]
are you using WLS?

**Comment by tjvandam** [comment]
Looks like I am not properly using WSL. I thought I did. I will install WSL and retry. Will that help? However, I still do not understand why my validation fails.

**Comment by Jaime-Trinidad** [comment]
@tjvandam in `README` are the instruction to update npm and Go on WLS, I will check what is happening, also I fixed the files and create #250 please close #247  PR, and if you are ok with new PR close this one, errors on WLS will be on issues.

**Pull request closed without merging**
