### PR TITLE
Add Yobiiq as vendor

### PR DESCRIPTION
**Pull request by dhakke**
#### Summary

Added Yobiiq as vendor and the SD1001 device./

#### Changes

- ...
- ...

#### Checklist for Reviewers

- [ ] Title and description should be descriptive (Not just a serial number for example).
- [ ] `profileIDs` should not be `vendorID` and should be a unique value for every profile.
- [ ] All devices should be listed in the vendor's `index.yaml` file.
- [ ] Firmware versions can not be changed.
- [ ] At least 1 image per device and should be transparent.

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Comment by yobiiq-fostin** [comment]
Hi @johanstokking @Jaime-Trinidad 
Could you please approve and validate the workflow for our PR? 
Thank you for your time and feedback!

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by Jaime-Trinidad** [comment]
Hi @dhakke please update the branch so I can merge it. Thanks

**Comment by Jaime-Trinidad** [comment]
@dhakke  please run `make validate fmt`

**Comment by yobiiq-fostin** [comment]
Hi @Jaime-Trinidad 
The branch is updated. You can now merge it.

**Pull request merged**
