### PR TITLE
Add vendor ioThings and device ioTracker 3

### PR DESCRIPTION
**Pull request by Bertje**
#### Summary

Add vendor ioThings and device ioTracker 3

#### Changes

Initial addition

#### Notes for Reviewers

Replaces this PR: https://github.com/TheThingsNetwork/lorawan-devices/pull/332

#### Release Notes

N/A

### CODE REVIEW

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by Jaime-Trinidad** [comment]
@Bertje Thanks for adding devices, please update this branch so I can merge it.

**Comment by Bertje** [comment]
@Jaime-Trinidad Updated. Please let me know if I need to do anything in addition to this.

**Comment by Jaime-Trinidad** [comment]
Hi @Bertje due the problems the rebase is generating I open #353, take a look to it.

**Comment by Bertje** [comment]
Thanks @Jaime-Trinidad. Looking forward to Johan's approval. I presume I don't have to do anything for this PR, correct?
Any idea what went wrong? Should I do something differently next time?

**Comment by Jaime-Trinidad** [comment]
Hi @Bertje exactly you don't have to make anything else in this PR, I will close it, it can be open any time. Thanks

**Pull request closed without merging**
