### PR TITLE
Introduce Tinovi vendor

### PR DESCRIPTION
**Pull request by datatoi**
#### Summary

Introduce Tinovi vendor

#### Changes

- added vendor/tinovi
- updated vendor/index.yaml

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Comment by Jaime-Trinidad** [comment]
@datatoi thank you for adding this, please run `make validate fmt`

**Comment by Jaime-Trinidad** [comment]
Hi @datatoi please rebase this branch so we can merge it. Thank you.

**Comment by datatoi** [comment]
Runing 'make validate fmt' on Ubuntu  WSL on Windows 10 , no failures ....

**Comment by Jaime-Trinidad** [comment]
Hi @datatoi files are good, can you please use images without background, when devices are deploy they also publish in [dev rep page.](https://www.thethingsnetwork.org/device-repository/) 
Also run `make deps` so `package-lock.json` return to the version, this file must not be modified.

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by Jaime-Trinidad** [comment]
@datatoi thanks for your submission

**Pull request merged**
