### PR TITLE
Decoder update and support for EU868, AU915 and AS923 channel plans

### PR DESCRIPTION
**Pull request by mvujovic-vb**
#### Summary
Decoder update and support for EU868, AU915 and AS923 channel plans

#### Changes

- Decoder is updated to v2.1.0.
- Profiles updated to add support for Channel Plans: EU868, AU915 and AS923

#### Checklist for Reviewers

- [ ] Title and description should be descriptive (Not just a serial number for example).
- [ ] `profileIDs` should not be `vendorID` and should be a unique value for every profile.
- [ ] All devices should be listed in the vendor's `index.yaml` file.
- [ ] Firmware versions can not be changed.
- [ ] At least 1 image per device and should be transparent.

### CODE REVIEW

**Comment by Jaime-Trinidad** [comment]
Hi @mvujovic-vb can you update the branch please

**Comment by mvujovic-vb** [comment]
@Jaime-Trinidad Done.

**Comment by mvujovic-vb** [comment]
@Jaime-Trinidad when we can expect merging? It's almost 2 months from the moment we submitted the PR.

**Comment by LDannijs** [comment]
@mvujovic-vb could you update the branch? Then ill have Jaime look at it when it is done.

**Comment by mvujovic-vb** [comment]
@LDannijs, done.

**Review by Jaime-Trinidad — APPROVED** [review]

**Pull request merged**
