### PR TITLE
Add MCF88 devices

### PR DESCRIPTION
**Pull request by francozampicinini**
#### Summary

...

#### Changes

- new sensors added

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Comment by johanstokking** [comment]
@francozampicinini thanks for your iteration.

The issue is now that there are a few sensors mentioned that we don't support (yet). Can you list all the sensors that you have? What I see now is:

- bvoc
- energy
- power
- time
- digital output

Note that we do have `current` and `voltage`. What do you mean with `energy` and `power`?

We also added `uv`, `digital input`, `solar radiation` and `rainfall`.

`digital output` is not a sensor. Apart from `sensors`, we might add a section `actuators`. In any case, we shouldn't add them to sensors.

Other validation errors are caused by:

1. Missing dimensions. You can remove the entire `dimensions` section; it's optional. But when it is set, you should enter numbers in millimeters
2. Missing codec files that are referenced `mcf88-lw12voc-codec`
3. Missing file `mcf-lw12lwws00.jpg`
4. Missing `classCTimeout` value. This is a number in seconds that the LNS uses to retry downlink messages in class C that are to be answered

**Comment by francozampicinini** [comment]
Hi, 

thanks for the update.

 

Energy is the amount of power during a period, in Wh, power is the istantaneous power in W.

 

Here the list:

 

  - temperature

  - humidity

  - barometer

  - wind speed

  - wind direction

  - rainfall

  - UV

  - dust

  - 0-10V input

  - pulses

  - frequency

  - RS232

  - RS485

  - 4-20mA input

  - digital input

  - digital output

  - temperature

  - humidity

  - barometer

  - light

  - bvoc

  - co2

  - voltage

  - current

  - energy

  - power

  - time

  - pulses

  - frequency  

 

So instead digital out I should use “actuator”?

 

Thanks

 

Da: Johan Stokking <notifications@github.com> 
Inviato: lunedì 11 gennaio 2021 15:46
A: TheThingsNetwork/lorawan-devices <lorawan-devices@noreply.github.com>
Cc: francozampicinini <franco.zampicinini@mcf88.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [TheThingsNetwork/lorawan-devices] Mcf88 (#48)

 

@francozampicinini <https://github.com/francozampicinini>  thanks for your iteration.

The issue is now that there are a few sensors mentioned that we don't support (yet). Can you list all the sensors that you have? What I see now is:

*	bvoc
*	energy
*	power
*	time
*	digital output

Note that we do have current and voltage. What do you mean with energy and power?

We also added uv, digital input, solar radiation and rainfall.

digital output is not a sensor. Apart from sensors, we might add a section actuators. In any case, we shouldn't add them to sensors.

Other validation errors are caused by:

1.	Missing dimensions. You can remove the entire dimensions section; it's optional. But when it is set, you should enter numbers in millimeters
2.	Missing codec files that are referenced mcf88-lw12voc-codec
3.	Missing file mcf-lw12lwws00.jpg
4.	Missing classCTimeout value. This is a number in seconds that the LNS uses to retry downlink messages in class C that are to be answered

**Comment by johanstokking** [comment]
> Energy is the amount of power during a period, in Wh, power is the istantaneous power in W.

OK. Added `energy` and `power`. We might add a unit later.

> Here the list:
> - temperature - humidity - barometer - wind speed - wind direction - rainfall - UV - dust

These are there now. Everything is lowercase so `uv`.

> - 0-10V input

This is `voltage`. We might add a scale later.

> - pulses - frequency

We now have `pulse count` and `pulse frequency`

> - RS232 - RS485

These are `auxiliary` w.r.t. sensors. We might add a new section "appliances" or "connectors" later.

> - 4-20mA input

This is `current`

> - digital input - digital output

`digital input` exists now, `digital output` is not a sensor.

> - temperature - humidity - barometer - light - bvoc - co2 - voltage - current - energy - power - time - pulses - frequency

Added `bvoc` and `time`. For the rest, see above. The others already exist.

> So instead digital out I should use “actuator”? Thanks

Actuator is currently not in the schema. We might add that later.

**Comment by francozampicinini** [comment]
Updated.

Still error:

 

mcf88: mcf-lw12co2: invalid: .sensors[4] should be equal to one of the allowed values 

 <https://github.com/TheThingsNetwork/lorawan-devices/pull/48/checks?check_run_id=1693537326#step:6:58> 58npm ERR! code ELIFECYCLE 

 <https://github.com/TheThingsNetwork/lorawan-devices/pull/48/checks?check_run_id=1693537326#step:6:59> 59npm ERR! errno 1 

 <https://github.com/TheThingsNetwork/lorawan-devices/pull/48/checks?check_run_id=1693537326#step:6:60> 60npm ERR! lorawan-devices@1.0.0 validate: `node bin/validate.js` 

 <https://github.com/TheThingsNetwork/lorawan-devices/pull/48/checks?check_run_id=1693537326#step:6:61> 61npm ERR! Exit status 1 

 <https://github.com/TheThingsNetwork/lorawan-devices/pull/48/checks?check_run_id=1693537326#step:6:62> 62npm ERR! 

 <https://github.com/TheThingsNetwork/lorawan-devices/pull/48/checks?check_run_id=1693537326#step:6:63> 63npm ERR! Failed at the lorawan-devices@1.0.0 validate script. 

 <https://github.com/TheThingsNetwork/lorawan-devices/pull/48/checks?check_run_id=1693537326#step:6:64> 64npm ERR! This is probably not a problem with npm. There is likely additional logging output above. 

 <https://github.com/TheThingsNetwork/lorawan-devices/pull/48/checks?check_run_id=1693537326#step:6:65> 65 

 <https://github.com/TheThingsNetwork/lorawan-devices/pull/48/checks?check_run_id=1693537326#step:6:66> 66npm ERR! A complete log of this run can be found in: 

 <https://github.com/TheThingsNetwork/lorawan-devices/pull/48/checks?check_run_id=1693537326#step:6:67> 67npm ERR! /home/runner/.npm/_logs/2021-01-13T08_03_40_017Z-debug.log 

 <https://github.com/TheThingsNetwork/lorawan-devices/pull/48/checks?check_run_id=1693537326#step:6:68> 68Makefile:36: recipe for target 'validate' failed 

 <https://github.com/TheThingsNetwork/lorawan-devices/pull/48/checks?check_run_id=1693537326#step:6:69> 69make: *** [validate] Error 1 

 <https://github.com/TheThingsNetwork/lorawan-devices/pull/48/checks?check_run_id=1693537326#step:6:70> 70Error: Process completed with exit code 2.

 

 

 

Not able to make validate on Visual Studio for Windows:

 

+ make validate

+ ~~~~

    + CategoryInfo          : ObjectNotFound: (make:String) [], CommandNotFoundException

    + FullyQualifiedErrorId : CommandNotFoundException

 

 

Thanks, 

Franco 

 

Da: Johan Stokking <notifications@github.com> 
Inviato: mercoledì 13 gennaio 2021 08:58
A: TheThingsNetwork/lorawan-devices <lorawan-devices@noreply.github.com>
Cc: francozampicinini <franco.zampicinini@mcf88.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [TheThingsNetwork/lorawan-devices] Mcf88 (#48)

 

Energy is the amount of power during a period, in Wh, power is the istantaneous power in W.

OK. Added energy and power. We might add a unit later.

Here the list:

*	temperature - humidity - barometer - wind speed - wind direction - rainfall - UV - dust

These are there now. Everything is lowercase so uv.

*	0-10V input

This is voltage. We might add a scale later.

*	pulses - frequency

We now have pulse count and pulse frequency

*	RS232 - RS485

These are auxiliary w.r.t. sensors. We might add a new section "appliances" or "connectors" later.

*	4-20mA input

This is current

*	digital input - digital output

digital input exists now, digital output is not a sensor.

*	temperature - humidity - barometer - light - bvoc - co2 - voltage - current - energy - power - time - pulses - frequency

Added bvoc and time. For the rest, see above. The others already exist.

So instead digital out I should use “actuator”? Thanks

Actuator is currently not in the schema. We might add that later.

**Comment by francozampicinini** [comment]
Error on loading image:

 

mcf88: mcf-lw06davk: load image ./vendor/mcf88/mcf-lwws00.jpg: Error: ENOENT: no such file or directory, open '/home/runner/work/lorawan-devices/lorawan-devices/vendor/mcf88/mcf-lwws00.jpg'

 

also file name must be lowercase?

 

 

Da: Johan Stokking <notifications@github.com> 
Inviato: mercoledì 13 gennaio 2021 08:58
A: TheThingsNetwork/lorawan-devices <lorawan-devices@noreply.github.com>
Cc: francozampicinini <franco.zampicinini@mcf88.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [TheThingsNetwork/lorawan-devices] Mcf88 (#48)

 

Energy is the amount of power during a period, in Wh, power is the istantaneous power in W.

OK. Added energy and power. We might add a unit later.

Here the list:

*	temperature - humidity - barometer - wind speed - wind direction - rainfall - UV - dust

These are there now. Everything is lowercase so uv.

*	0-10V input

This is voltage. We might add a scale later.

*	pulses - frequency

We now have pulse count and pulse frequency

*	RS232 - RS485

These are auxiliary w.r.t. sensors. We might add a new section "appliances" or "connectors" later.

*	4-20mA input

This is current

*	digital input - digital output

digital input exists now, digital output is not a sensor.

*	temperature - humidity - barometer - light - bvoc - co2 - voltage - current - energy - power - time - pulses - frequency

Added bvoc and time. For the rest, see above. The others already exist.

So instead digital out I should use “actuator”? Thanks

Actuator is currently not in the schema. We might add that later.

**Comment by johanstokking** [comment]
@francozampicinini yes, that's it, thanks!

**Review by johanstokking — APPROVED** [review]

**Pull request merged**
