### PR TITLE
Delete duplicated

### PR DESCRIPTION
**Pull request by Jaime-Trinidad**
Thermokon was duplicated in the root

#### Summary

...

#### Changes

- ...
- ...

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Comment by Jaime-Trinidad** [comment]
Hi @ysmilda I delete the duplicated can you review it so I can merge it

**Review by ysmilda — CHANGES_REQUESTED** [review]
When the files were added to the root they were also updated, those changes are now lost. Can you copy the files into the `vendors` folder instead of just deleting them?

**Comment by Jaime-Trinidad** [comment]
> When the files were added to the root they were also updated, those changes are now lost. Can you copy the files into the `vendors` folder instead of just deleting them?

Yeah, they are already there I verify before deleting them from the root, and are the same, that's why I didn't copy them to not duplicate

**Comment by Jaime-Trinidad** [comment]
@ysmilda review done including some fixes

**Review by ysmilda — APPROVED** [review]
LGTM!

**Pull request merged**
