### PR TITLE
Ellenex updates to title, ouis and addition of 14 new devices

### PR DESCRIPTION
**Pull request by sft-s1-ellenex**
Updated our title and oui

### CODE REVIEW

**Comment by sft-s1-ellenex** [comment]
The update also consists of 14 new devices from Ellenex. If you need any further information from us, we will be happy to provide in order to complete this request as soon as possible. Thanks in advance.

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by Jaime-Trinidad** [comment]
@sft-s1-ellenex thanks for the update, please rebase the PR

**Comment by sft-s1-ellenex** [comment]
@Jaime-Trinidad thanks for approving the PR. Rebased PR from Master.

**Comment by sft-s1-ellenex** [comment]
Hey @Jaime-Trinidad We have updated it to the latest changes again. Please merge the PR so I can close this.

**Pull request merged**
