### PR TITLE
Add: add Seeed two Lora dev boards

### PR DESCRIPTION
**Pull request by BilltheWorld**
#### Summary

...

#### Changes

Add Seeed two Lora dev boards
- ...
- ...

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Comment by BilltheWorld** [comment]
Hello! I am "chenxixiya" and this is my second account, trying to re-push the seeed dev board files. Looks like it's working! I think is my organization that caused the problem before as I forked the repo under my organization. Anyway, would you mind help me merging it? Thank you very much.

**Comment by Jaime-Trinidad** [comment]
Hi @BilltheWorld there is missing one file `loraeminidevboard-e5.yaml` can you add it please

**Comment by BilltheWorld** [comment]
Hello, I repush the file here. When I checked the commits, I thought I changed some other files at the same time. But it's all good, I have changed it back. Sorry to bother you with these so much.

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by Jaime-Trinidad** [comment]
> Hello, I repush the file here. When I checked the commits, I thought I changed some other files at the same time. But it's all good, I have changed it back. Sorry to bother you with these so much.

No problem, everything is right now, thanks for adding the devices

**Pull request merged**
