### PR TITLE
add new device and change pictures for device

### PR DESCRIPTION
**Pull request by yosensi**
#### Summary

chnaged pictures of the devices, add people counter

#### Changes

- description YO Pulse and YO modbbus, sensors in YO modbus & YO analog (yaml files)
- added new people counter device

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Review by yosensi — COMMENTED** [review]
added new photo for devices, changed index, added yo people counter

**Review by yosensi — COMMENTED** [review]
deleted email

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by yosensi** [comment]
@Jaime-Trinidad I did validation format and every file in Visual studio for Yosensi vendor is valid. Idk why here when it trys to do it again (I mean run prettier function) it fails. Can you suggest something what I can do in this situation?

**Review by yosensi — COMMENTED** [review]
deleted empty lines in modbus.yaml

**Review by yosensi — COMMENTED** [review]
all changes aproved

**Pull request merged**
