### PR TITLE
Add Develiot to vendor

### PR DESCRIPTION
**Pull request by tishka25**
#### Summary

Added Develiot devices to the vendor's directory
...

#### Changes

- Created Develiot vendor to the vendor list
- Created Remote Water Meter device with the corresponding codec, profile and general information
- Created Urban Air Quality Monitoring Station device with the corresponding profile and general information

### CODE REVIEW

**Comment by johanstokking** [comment]
Thanks @tishka25 !

Looks perfect.

Please remove `package-lock.json`. You can also rebase on top of latest `master` as we fixed the dependency issue.

Otherwise it's good to go and I'll merge.

**Review by johanstokking — APPROVED** [review]

**Comment by johanstokking** [comment]
@tishka25 thanks. Please drop the last two commits. Make sure you have the same Node and NPM versions as described in `README`

**Comment by johanstokking** [comment]
@tishka25 you may also want to give write permissions to your branch so that I can make these changes accordingly.

**Comment by tishka25** [comment]
@johanstokking rebase is done and I thing I correctly resolved the merge conflicts on my side. 
Thanks in advance!

**Comment by johanstokking** [comment]
@tishka25 unfortunately the rebase isn't good, see the changes here. I had to do this on our branch as you didn't allow edits to yours. See https://github.com/TheThingsNetwork/lorawan-devices/pull/65

**Pull request closed without merging**
