### PR TITLE
Modified and added new Acrios devices

### PR DESCRIPTION
**Pull request by ACR-MLY**
Added new Acrios devices, and fixed few things.

### CODE REVIEW

**Comment by ACR-MLY** [comment]
@Jaime-Trinidad Hello again, I created new pull request (I had to clean few things I made in previous one). This time I deleted only one file (new photo) and changed name of "acr-cv-101l-m-eac" to capital latters  (I guess this is the reason why it won't validate?). Thanks in advance.

**Comment by Jaime-Trinidad** [comment]
@ACR-MLY I made some fixes, review them is important that all files names must be in lower case, there are still some fixes you have to make, please run `make deps` `package-lock.json` and `package.json` don't have to change, the deleted file is causing problems, you don't have to erase this PR maybe work on this.

**Comment by Jaime-Trinidad** [comment]
hi @ACR-MLY any update here?

**Comment by ACR-MLY** [comment]
Hi @Jaime-Trinidad , sorry, I didn't had much time until now to fix it ... it should be okay now. Thank you

**Comment by Jaime-Trinidad** [comment]
Thank you @ACR-MLY

**Pull request merged**
