### PR TITLE
Add sensecap s2120 and update s2100 decoder file

### PR DESCRIPTION
**Pull request by Kway99**
#### Summary

Add sensecap s2120 and update s2100 decoder file.

#### Changes

- Add sensecap s2120
- update s2100 decoder file

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Comment by Kway99** [comment]
Hi  Jamie,

This is Lee from Seeed SenseCAP team
Based on your comments, I have made some modifications:
signed CLA and change sensecap-profile.yaml file.
I closed the previous request (https://github.com/TheThingsNetwork/lorawan-devices/pull/552) and request again here.
Many thanks for your attention and sorry for causing inconvenience.

Best Regards!

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by Jaime-Trinidad** [comment]
Hi @Kway99 thanks, please check `codec sensecap2120-8-in-1-codec` and image from the same device, I made some fixes on it, but still missing these checks

**Comment by Kway99** [comment]
Hi, @Jaime-Trinidad Really thanks for helping me modify. Already checked, and I don't know if there is anything else that can be changed.

**Comment by johanstokking** [comment]
@Kway99 thanks. I had to export one image to PNG; it had the PNG extension but it was a different image format instead.

I now have the following validation issue:

```
sensecap: sensecaps2120-8-in-1: EU863-870: payload codec sensecap2120-8-in-1-codec invalid
./vendor/sensecap/sensecap2100-decoder.js:decodeUplink: output {"data":{"err":0,"messages":[[{"measurementId":"4097","measurementValue":25.6,"type":"Air Temperature"},{"measurementId":"4098","measurementValue":1,"type":"Air Humidity"},{"measurementId":"4099","measurementValue":16777473,"type":"Light Intensity"},{"measurementId":"4190","measurementValue":0.2,"type":"UV Index"},{"measurementId":"4105","measurementValue":10.6,"type":"Wind Speed"}],[{"measurementId":"4097","measurementValue":2.1,"type":"Air Temperature"},{"measurementId":"4098","measurementValue":1,"type":"Air Humidity"},{"measurementId":"4099","measurementValue":50344177,"type":"Light Intensity"},{"measurementId":"4190","measurementValue":"-0.9","type":"UV Index"},{"measurementId":"4105","measurementValue":1126.5,"type":"Wind Speed"}],[{"Battery(%)":0,"Firmware Version":"19.20","Hardware Version":"9.12","gpsInterval":7620,"measureInterval":15660}]],"payload":"010100010100010102006A01001501030030F1F72C010400090C13140105007F4D0000010600000000004CBE","valid":true}} does not match {"data":{"valid":true,"err":0,"payload":"010100010100010102006A01001501030030F1F72C010400090C13140105007F4D0000010600000000004CBE","messages":[{"type":"upload_sensor_id","channel":1,"sensorId":"2CF7F1301500016A"}]}}
```

Can you fix this? You can run the validation yourself with `make validate`.

**Comment by johanstokking** [comment]
I think that you need to change the expected output to:

```json
{
  "data": {
    "err": 0,
    "messages": [
      [
        {
          "measurementId": "4097",
          "measurementValue": 25.6,
          "type": "Air Temperature"
        },
        {
          "measurementId": "4098",
          "measurementValue": 1,
          "type": "Air Humidity"
        },
        {
          "measurementId": "4099",
          "measurementValue": 16777473,
          "type": "Light Intensity"
        },
        {
          "measurementId": "4190",
          "measurementValue": 0.2,
          "type": "UV Index"
        },
        {
          "measurementId": "4105",
          "measurementValue": 10.6,
          "type": "Wind Speed"
        }
      ],
      [
        {
          "measurementId": "4097",
          "measurementValue": 2.1,
          "type": "Air Temperature"
        },
        {
          "measurementId": "4098",
          "measurementValue": 1,
          "type": "Air Humidity"
        },
        {
          "measurementId": "4099",
          "measurementValue": 50344177,
          "type": "Light Intensity"
        },
        {
          "measurementId": "4190",
          "measurementValue": "-0.9",
          "type": "UV Index"
        },
        {
          "measurementId": "4105",
          "measurementValue": 1126.5,
          "type": "Wind Speed"
        }
      ],
      [
        {
          "Battery(%)": 0,
          "Firmware Version": "19.20",
          "Hardware Version": "9.12",
          "gpsInterval": 7620,
          "measureInterval": 15660
        }
      ]
    ],
    "payload": "010100010100010102006A01001501030030F1F72C010400090C13140105007F4D0000010600000000004CBE",
    "valid": true
  }
}
```

**Comment by Kway99** [comment]
Hi @johanstokking 
Thank you guys for doing so much for me, I have already fixed the above issues.
Besides, every time when I run make validate, it goes like that:
image
image
It seems stuck at the previous steps, so I can't move the procedure on.

**Review by johanstokking — APPROVED** [review]

**Comment by Kway99** [comment]
Yes, I can run 'make deps' succeed. I'm using a mac terminal to run these.

**Comment by Kway99** [comment]
Hello, does this validator indicate where there is an error? cause we don't know what's wrong either.

**Comment by johanstokking** [comment]
@Kway99 this is what the decoder produces:

```json
{
  data: {
    err: 0,
    messages: [ [Array], [Array], [Array] ],
    payload: '010100010100010102006A01001501030030F1F72C010400090C13140105007F4D0000010600000000004CBE',
    valid: true
  }
}
```

Where `data.messages` is:

```json
[
  [
    {
      measurementId: '4097',
      measurementValue: 25.6,
      type: 'Air Temperature'
    },
    {
      measurementId: '4098',
      measurementValue: 1,
      type: 'Air Humidity'
    },
    {
      measurementId: '4099',
      measurementValue: 16777473,
      type: 'Light Intensity'
    },
    { measurementId: '4190', measurementValue: 0.2, type: 'UV Index' },
    {
      measurementId: '4105',
      measurementValue: 10.6,
      type: 'Wind Speed'
    }
  ],
  [
    {
      measurementId: '4097',
      measurementValue: 2.1,
      type: 'Air Temperature'
    },
    {
      measurementId: '4098',
      measurementValue: 1,
      type: 'Air Humidity'
    },
    {
      measurementId: '4099',
      measurementValue: 50344177,
      type: 'Light Intensity'
    },
    {
      measurementId: '4190',
      measurementValue: '-0.9',
      type: 'UV Index'
    },
    {
      measurementId: '4105',
      measurementValue: 1126.5,
      type: 'Wind Speed'
    }
  ],
  [
    {
      'Battery(%)': 0,
      'Firmware Version': '19.20',
      'Hardware Version': '9.12',
      gpsInterval: 7620,
      measureInterval: 15660
    }
  ]
]
```

This second block of measurements seems off; those values don't look right.

It's the test case `Report sensor's metadatas` in `vendor/sensecap/sensecap2120-8-in-1-codec.yaml`. The expected output is just one item in `messages` but as you can see there are many (and I think partly faulty).

**Comment by Kway99** [comment]
@johanstokking Thanks, I got it, there is one more question. Could we just delete the example directly? cause I see there is a note that is optional.
image

**Comment by johanstokking** [comment]
It's optional, but we will be using examples more extensibly in the future, for example, to generate simulated events. So it's better to keep them if it's not too much of a hassle.

To be honest, I think there's a problem with the decoder here as the output doesn't seem correct. But I might be wrong.

**Comment by Kway99** [comment]
Thanks~I understand, we find it's just the raw payload('010100010100010102006A01001501030030F1F72C010400090C13140105007F4D0000010600000000004CBE') in the example we wrote before is wrong, so the output seems not correct. The decoder was already tested by our R&D previously. we're thinking about deleting the example directly. I'm not very sure if this will affect the validation results.

**Comment by johanstokking** [comment]
@Kway99 so the output of `010100010100010102006A01001501030030F1F72C010400090C13140105007F4D0000010600000000004CBE` is:

```json
{
  "data": {
    "valid": true,
    "err": 0,
    "payload": "010100010100010102006A01001501030030F1F72C010400090C13140105007F4D0000010600000000004CBE",
    "messages": [
      {
        "type": "upload_sensor_id",
        "channel": 1,
        "sensorId": "2CF7F1301500016A"
      }
    ]
  }
}
```

There is nothing else in there?

**Comment by Kway99** [comment]
@johanstokking this output is copied from the previous codec file which means nothing for added s2120(8-in1) here, so I have deleted the whole example in the codec file of 8-in-1. Where is this stuck now?

**Comment by johanstokking** [comment]
The issue is in `sensecap2100-codec.yaml`: https://github.com/TheThingsNetwork/lorawan-devices/pull/560/files#diff-07ccdac4a8db7280404be70d3c4bb1effe3dfd50053e70b1ee417e6fce3fa91eR4. I tested these individual test cases and they all three fail.

**Comment by Kway99** [comment]
@johanstokking Now, I have deleted three sets of examples, could you please try again with the validate? Thanks a lot.

**Pull request merged**
