### PR TITLE
Proposal to upgrade schema to Json 2020-12

### PR DESCRIPTION
**Pull request by peter-quandify**
#### Summary
The `schema.json` and `lib/payload.json`uses JSON schema draft 07. 
This PR is a proposal to upgrade it to draft 2020-12.

#### Changes
- Updated `schema.json` to draft 2020-12 format
- Updated `lib/payload.json` to draft 2020-12 format
- Updated `bin/validate.js`
  - Ajv 6.x -> 8.x that support 2020-12 format
  - Ajv compile -> getSchema
  - Ajv breaking change dataPath -> instancePath
- Clean-up of unused dependencies
- Upgraded Ajv cli and applied security patch

#### Checklist for Reviewers

- [ ] Title and description should be descriptive (Not just a serial number for example).
- [ ] `profileIDs` should not be `vendorID` and should be a unique value for every profile.
- [ ] All devices should be listed in the vendor's `index.yaml` file.
- [ ] Firmware versions can not be changed.
- [ ] At least 1 image per device and should be transparent.

#### Notes for Reviewers
The upgrade to JSON schema draft 2020-12 made all `thermokon` productUrl invalid, which needs to fixed before merge.

#### Release Notes
Upgraded JSON schema for validation to draft 2020-12

### CODE REVIEW

**Comment by johanstokking** [comment]
@peter-quandify thanks a lot. You can append 7ed71bdf8 here; I don't have permissions to push to your branch.

**Comment by johanstokking** [comment]
> @johanstokking Done! But who should report the licens/cla ?

That would be everyone in the commit trail based on email address, so `p*.e*@quandify.com`. Do you have a GitHub account associated with that?

**Comment by peter-quandify** [comment]
I have already signed the CLA a while ago on that eamil, so I'm not sure why it says that

**Comment by peter-quandify** [comment]
Or you could merge your branch @johanstokking and delete this PR?

**Comment by johanstokking** [comment]
> I have already signed the CLA a while ago on that email, so I'm not sure why it says that

Let's not bother then!

Thanks again!

**Pull request merged**
