### PR TITLE
Add opensource device - esp32-paxcounter

### PR DESCRIPTION
**Pull request by Drasek**
#### Summary
This is the first release of the necessary files for the [https://github.com/cyberman54/ESP32-Paxcounter](https://github.com/cyberman54/ESP32-Paxcounter) and because there is no opensource/hardware/community vendor in this repo atm we added a opensource "vendor" aswell - could maybe be used for all the bigger opensource/hardware/community projects in the future. We provide only the software for dozens of hardware devices from different vendors/makers.

#### Changes
- added opensource to index.yaml
- added opensource folder to vendor
- added esp32-paxcounter-codec.yaml
- added esp32-paxcounter-packed.js
- added esp32-paxcounter-profile-eu868.yaml
- added esp32-paxcounter-profile-us915.yaml
- added esp32-paxcounter.yaml
- added index.yaml

#### Notes for Reviewers
This first addition of the "opensource" vendor will allow us, the community, to add devices to the lorawan-device repo aswell and support the users of our developed soft- & hardware to easily use it and add it to their V3 applications in the console of The Things Stack - Community Edition V3. Thank you very much!

#### Release Notes
- Added opensource / community projects vendor to cinlude bigger and stable community projects
- Added support for esp32-paxcounter v2.4.0
- Added support for esp32-paxcounter v3.0.0

### CODE REVIEW

**Comment by Jaime-Trinidad** [comment]
Hi @Drasek thanks for your submission, please can you check `esp32-paxcounter-codec.yaml` it send error when run validate in their different ports.

**Comment by Drasek** [comment]
@Jaime-Trinidad Now its validating on my end - had a lot of bytes in the wrong order (lsb vs msb).

**Comment by Jaime-Trinidad** [comment]
> @Jaime-Trinidad Now its validating on my end - had a lot of bytes in the wrong order (lsb vs msb).

Thanks, please run make validate fmt

**Comment by Drasek** [comment]
I can only run "makge validate fmt" if i remove a lot of vendors from the yaml else i get following error:

> decentlab: dl-pr36: Error: load image ./vendor/decentlab/dl-pr36.jpg: Error: EMFILE: too many open files, open '/home/caspar/lorawan-devices/vendor/decentlab/dl-pr36.jpg'
> make: *** [Makefile:37: validate] Error 1

I am using a windows 10 install with the subsystem for linux. Any thing i can change in my configuration of the subsystem to make it work?

**Comment by Drasek** [comment]
Ok needed to change the ulimit settings for the subsystem and did need to login with "su myusername" again in the runing session to make it work... do not let me rant about windows and linux here, sorry... did "make validate fmt" and commited the changes, what now? Thank you very much!

**Review by Jaime-Trinidad — APPROVED** [review]

**Comment by Drasek** [comment]
Hello Jaime,

may i ask you how long it usually takes till the device list is updated in the Things Network Community Edition? Till their next release (2 weeks cycle atm or?) or shorter or longer? Do you know? Thank you very much!

Cheers

Caspar

**Pull request merged**
