### PR TITLE
Add makerfabs

### PR DESCRIPTION
**Pull request by cooper99-ui**
#### Summary

Add makerfabs

#### Changes

- ...
- ...

#### Checklist for Reviewers

- [ ] Title and description should be descriptive (Not just a serial number for example).
- [ ] `profileIDs` should not be `vendorID` and should be a unique value for every profile.
- [ ] All devices should be listed in the vendor's `index.yaml` file.
- [ ] Firmware versions can not be changed.
- [ ] At least 1 image per device and should be transparent.

#### Notes for Reviewers

...

#### Release Notes

- ...

### CODE REVIEW

**Comment by johanstokking** [comment]
Thanks @cooper99-ui. This diff is too large. At first glance, the file permissions are changed for a lot of files, leading to a massive diff. Also there are formatting changes in `bin/validate.js`. See https://github.com/TheThingsNetwork/lorawan-devices/pull/844/files. We only expect changed files there.

I would assume only `vendor/makerfabs` would be added and the vendor to be added to `vendor/index.yaml`. If you need help, let us know.

**Comment by cooper99-ui** [comment]
Dear Johan Stokking:
    I am very happy to receive your reply. Since this is the first time for me to deal with this matter, there may be many mistakes. I am very sorry for that. In fact, I only added the product file of our company and did not change other files. I did this in a Linux virtual machine environment, I don't know if this has any effect, because I watched the instructional video in a mac environment, the current situation is that I should start again or there is another solution. Looking forward to your reply again
    
        copper


***@***.***
 
From: Johan Stokking
Date: 2024-11-07 16:45
To: TheThingsNetwork/lorawan-devices
CC: cooper99-ui; Mention
Subject: Re: [TheThingsNetwork/lorawan-devices] Add makerfabs (PR #844)
Thanks @cooper99-ui. This diff is too large. At first glance, the file permissions are changed for a lot of files, leading to a massive diff. Also there are formatting changes in bin/validate.js. See https://github.com/TheThingsNetwork/lorawan-devices/pull/844/files. We only expect changed files there.
I would assume only vendor/makerfabs would be added and the vendor to be added to vendor/index.yaml. If you need help, let us know.

**Comment by johanstokking** [comment]
@cooper99-ui I think I fixed this for you. Can you check the change set here please?

**Comment by cooper99-ui** [comment]
hi,Johan Stokking
I have seen the changed part, which is the file I added. Thank you very much for your help. I have more than ten products to add to the repository later, do you think it is OK to operate like this product? Looking forward to your reply again

        cooper


***@***.***
 
From: Johan Stokking
Date: 2024-11-07 23:31
To: TheThingsNetwork/lorawan-devices
CC: cooper99-ui; Mention
Subject: Re: [TheThingsNetwork/lorawan-devices] Add makerfabs (PR #844)
@cooper99-ui I think I fixed this for you. Can you check the change set here please?

**Comment by johanstokking** [comment]
> hi,Johan Stokking I have seen the changed part, which is the file I added. Thank you very much for your help. I have more than ten products to add to the repository later, do you think it is OK to operate like this product? Looking forward to your reply again cooper

This product looks good, the codec too. I would rename the product name next time, it's all lowercase now.

The issue is likely caused by a code editor and/or file formatter. Best is to disable those.

**Comment by cooper99-ui** [comment]
hi,Johan Stokking, I have seen my product added to the repository, but I don't see our product optional on the ttn product selection page, do we need to wait for some time to see it? Now we want to see the display effect of this product first, and then we plan to add our next dozen products to the repository, we are looking forward to your reply again



***@***.***
 
From: Johan Stokking
Date: 2024-11-08 17:26
To: TheThingsNetwork/lorawan-devices
CC: cooper99-ui; Mention
Subject: Re: [TheThingsNetwork/lorawan-devices] Add makerfabs (PR #844)
hi,Johan Stokking I have seen the changed part, which is the file I added. Thank you very much for your help. I have more than ten products to add to the repository later, do you think it is OK to operate like this product? Looking forward to your reply again cooper
This product looks good, the codec too. I would rename the product name next time, it's all lowercase now.
The issue is likely caused by a code editor and/or file formatter. Best is to disable those.

**Comment by johanstokking** [comment]
@cooper99-ui it is listed here: https://www.thethingsnetwork.org/device-repository/devices/makerfabs/ath20/. In The Things Stack, it will be part of the next release.

**Comment by johanstokking** [comment]
@cooper99-ui please use `git clone` and stage and commit only changes in `vendor/makerfabs`. Please disable any automatic formatting extensions in your code editor. Then it should be good.

**Comment by cooper99-ui** [comment]
hi,Johan Stokking
I added some code for several products, but there were some problems in compiling and committing the code. I used make validate to compile the code without any problems, but I used make validate fmt to get an error saying "npm run format

> ***@***.*** format
> prettier --write schema.json "vendor/**/*.yaml" "bin/**/*.js"

sh: 1: prettier: not found
make: *** [Makefile:45: fmt] error 127 "I searched the Internet for some fixes, but still got this error when I ran this command. Another problem is that when I execute the make deps instruction, I have been failing to download and reporting that I cannot access the go server. However, my network is good. I hope you can help me to check these two problems and look forward to your reply.

        copper


***@***.***
 
From: Johan Stokking
Date: 2024-11-08 17:26
To: TheThingsNetwork/lorawan-devices
CC: cooper99-ui; Mention
Subject: Re: [TheThingsNetwork/lorawan-devices] Add makerfabs (PR #844)
hi,Johan Stokking I have seen the changed part, which is the file I added. Thank you very much for your help. I have more than ten products to add to the repository later, do you think it is OK to operate like this product? Looking forward to your reply again cooper
This product looks good, the codec too. I would rename the product name next time, it's all lowercase now.
The issue is likely caused by a code editor and/or file formatter. Best is to disable those.
―

**Pull request merged**
