### PR TITLE
Add MClimate devices

### PR DESCRIPTION
**Pull request by MClimate**
**Summary**

Added MClimate LoRaWAN devices.

**Changes**

- Added
  - mclimate-vicki
  - mclimate-t-valve
  - mclimate-t-flood
  - mclimate-ht-sensor
  - mclimate-aqi-sensor
-  Added `MClimate` to vendors list.

### CODE REVIEW

**Comment by benolayinka** [comment]
Looks like formatting is failing. Did you `make validate fmt` ?

**Review by benolayinka — COMMENTED** [review]
Looks good, but it will really help end users if you add codecs with at least uplink payload formatters. I'm okay with merging this as is, so it makes it on the Wall of Fame, and then you can add the codecs when you have time.

**Comment by benolayinka** [comment]
> Looks good, but it will really help end users if you add codecs with at least uplink payload formatters.

**Review by johanstokking — APPROVED** [review]

**Comment by lyubomiryanchev** [comment]
> Looks good, but it will really help end users if you add codecs with at least uplink payload formatters. I'm okay with merging this as is, so it makes it on the Wall of Fame, and then you can add the codecs when you have time.

Thanks for the input, we'll implement appropriate improvements. Please merge this pull request, so that our devices are displayed on the Wall of Fame. Appreciate it!

**Pull request merged**
